---
title: "ECON 712B - Problem Set 2"
author: "Alex von Hafften^[I worked on this problem set with a study group of Michael Nattinger, Andrew Smith, and Ryan Mather. I also discussed problems with Emily Case, Sarah Bass, and Danny Edgel.]"
date: "11/19/2020"
output: pdf_document
header-includes:
- \newcommand{\N}{\mathbb{N}}
- \newcommand{\Z}{\mathbb{Z}}
- \newcommand{\R}{\mathbb{R}}
- \newcommand{\Q}{\mathbb{Q}}
- \newcommand{\Lf}{\mathcal{L}}
- \newcommand{\graph}{\text{graph}}
- \usepackage{bm}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

1. In class, we only considered the growth model with inelastic labor supply. This problem relaxes that restriction. Consider the benchmark neoclassical growth model, with production function: $Y_t = F(K_t, A_t N_t)$ where $Y_t$ is output, $K_t$ is capital, $A_t$ is technology, and $N_t$ is labor, and $F$ has constant returns to scale and satisfies the usual assumptions. Technology grows exogenously at rate $g$: $A_{t+1} = (1+g) A_t$.  Capital depreciates at rate $\delta$ so (imposing the aggregate feasibility condition) we can write the law of motion for the capital stock as: $K_{t+1} = (1 - \delta) K_t + Y_t - C_t$. The representative household has time additive preferences given by: $\sum_{t=0}^\infty \beta^t u(C_t, 1 - N_t)$.  The population size is fixed, but the labor input $N_t \in [0,1]$ is now endogenous. This problem will consider the existence of a balanced growth path, which is defined as an equilibrium allocation where consumption, capital, wages $W_t$, and output all grow at the same constant rate, while interest rates $r_t$ and labor $N_t$ are constant.

(a) From conditions characterizing the equilibrium, find a system of equations that the endogenous variables $C_0$, $N_0$, $W_0$, $r_0$ must solve in a balanced growth path. (Initial capital $K_0$ is given.)

In a competitive equilibrium, households optimize, firms optimize, and markets clear.\footnote{Note on notation: In the original problem set, it specifies $w_t$ as wages that grow over time.  Here, I define $W_t$ as the real wage rate on labor $N_t$ and $w_t$ as the real wage rate on effective labor $A_tN_t$. In addition, I define $r_t$ as the real rental rate on capital.}

The household problem is 

\begin{align*}
\max_{\{(C_t, N_t, K_t, I_t)\}_{t=0}^\infty} & \sum_{t=0}^\infty \beta^t u(C_t, 1 - N_t) \\
\text{s.t. } & \sum_{t=0}^\infty p_t (C_t + I_t) = \sum_{t=0}^\infty p_t (r_t K_t + W_t N_t) + \pi_t \\
& K_{t+1} = (1 - \delta) K_t + I_t
\end{align*}

The firm problem is

$$
\max_{\{K_t^d, N_t^d\}_{t=0}^\infty} \sum_{t=0}^\infty p_t(F(K_t^d, A_t N_t^d) - r_tK_t^d - W_tN_t^d)
$$

Normalize consumption, capital, investment, and wages by technology: $c_t = \frac{C_t}{A_t}$, $k_t = \frac{K_t}{A_t}$, $i_t = \frac{I_t}{A_t}$, and $w_t = \frac{W_t}{A_t}$.

\pagebreak

The firm problem becomes:

$$
\max_{\{k_t^d, N_t^d\}_{t=0}^\infty} \sum_{t=0}^\infty p_t(F(A_tk_t^d, A_t N_t^d) - r_t A_t k_t^d - A_t w_t N_t^d)
$$

FOC [$k_t^d$]:\footnote{Note on notation: $F_1$ is the derivative with respect to the first argument of $F$ and $F_2$ is the derivative with respect to the second argument of $F$.}

$$
p_tF_1(A_tk_t^d, A_t N_t^d)A_t =  p_tA_tr_t \implies F_1(A_tk_t^d, A_t N_t^d) = r_t 
$$ 

FOC [$N_t^d$]:

$$
p_tF_2(A_tk_t^d, A_t N_t^d)A_t = p_tA_tw_t \implies F_2(A_tk_t^d, A_t N_t^d) = w_t
$$

Since $F$ has CRS $\implies F(K, N) = KF_1(K, N) + NF_2(K, N)$ by Euler's Theorem. Thus, for all $t$,

\begin{align*}
\pi_t 
&= p_t(F(A_tk_t^d, A_t N_t^d) - r_t A_t k_t^d - A_t w_t N_t^d) \\
&= p_t(A_tk_t^dF_1(A_tk_t^d, A_t N_t^d) + A_t N_t^dF_2(A_tk_t^d, A_t N_t^d) - r_t A_t k_t^d - A_t w_t N_t^d) \\
&= p_t(A_t k_t^d r_t + A_t N_t^dw_t - r_t A_t k_t^d - A_t w_t N_t^d) \\
&= 0
\end{align*}

The household problem becomes:

\begin{align*}
\max_{\{(c_t, N_t, i_t, k_t)\}_{t=0}^\infty} & \sum_{t=0}^\infty \beta^t u(A_tc_t, 1-N_t) \\
\text{s.t. } & \sum_{t=0}^\infty p_t (A_t c_t + A_t i_t) = \sum_{t=0}^\infty p_t (r_t A_t k_t + w_t A_t N_t) + (0) \\
& A_{t+1}k_{t+1} = (1 - \delta) A_{t}k_{t} + A_{t}i_{t} \\
\implies
\max_{\{(c_t, N_t, i_t, k_t)\}_{t=0}^\infty} & \sum_{t=0}^\infty \beta^t u(A_tc_t, 1-N_t) \\
\text{s.t. } & \sum_{t=0}^\infty p_t (c_t + i_t - r_t k_t - w_t N_t) = 0 \\
& i_{t} = (1+g)k_{t+1} - (1 - \delta) k_{t} \\
\implies
\max_{\{(c_t, N_t, i_t, k_t)\}_{t=0}^\infty} & \sum_{t=0}^\infty \beta^t u(A_tc_t, 1-N_t) \\
\text{s.t. } & \sum_{t=0}^\infty p_t (c_t + (1+g)k_{t+1} - (1 - \delta) k_{t} - r_t k_t - w_t N_t) = 0
\end{align*}

\pagebreak

Define Legrangian:

$$
\Lf 
= \sum_{t=0}^\infty \beta^t u(A_tc_t, 1-N_t) 
+ \lambda\Bigg[\sum_{t=0}^\infty p_t (c_t + (1+g)k_{t+1} - (1 - \delta) k_{t} - r_t k_t - w_t N_t)\Bigg]
$$

FOC [$c_t$]:\footnote{Note on notation: $u_1$ is the derivative with respect to the first argument of $u$ and $u_2$ is the derivative with respect to the second argument of $u$.}

$$
0 = \beta^t u_1(A_tc_t, 1-N_t)A_t + \lambda p_t \\
\implies
-\lambda = \frac{\beta^t u_1(A_tc_t, 1-N_t)A_t}{p_t}
$$

FOC [$c_{t+1}$]:

$$
0 = \beta^{t+1} u_1(A_{t+1}c_{t+1}, 1-N_{t+1})A_{t+1} + \lambda p_{t+1} \\
\implies 
-\lambda = \frac{\beta^{t+1} u_1(A_{t+1}c_{t+1}, 1-N_{t+1})A_{t+1}}{p_{t+1}}
$$

FOC [$c_t$] and FOC [$c_{t+1}$] imply:

$$
\frac{\beta^t u_1(A_tc_t, 1-N_t)A_t}{p_t} = \frac{\beta^{t+1} u_1(A_{t+1}c_{t+1}, 1-N_{t+1})A_{t+1}}{p_{t+1}} \\ 
\implies 
u_1(A_tc_t, 1-N_t) = \frac{\beta (1 + g )}{q_{t+1}}u_1(A_{t+1}c_{t+1}, 1-N_{t+1})
$$

where $q_{t+1} = \frac{p_{t+1}}{p_t}$.

FOC [$N_t$]

$$
0 = \beta^t u_2(A_tc_t, 1-N_t) (-1) - \lambda p_tw_t N_t
$$

FOC [$N_{t+1}$]

$$
0 = \beta^{t+1} u_2(A_{t+1}c_{t+1}, 1-N_{t+1}) (-1) - \lambda p_{t+1} w_{t+1} N_{t+1}
$$

These conditions imply

$$
w_tu_1(C_t, 1-N_t) = - u_2(C_t, 1-N_t)
$$

No arbitrage condition:

$$
p_t = (r_{t+1} + 1 - \delta)p_{t+1}
$$

The law of motion of capital implies:

$$
\frac{K_{t+1}}{A_t}\frac{A_{t+1}}{A_{t+1}} = (1-\delta) \frac{K_t}{A_t} + \frac{F(K_t, A_t N_t)}{A_t} - \frac{C_t}{A_t}\\
\implies
k_{t+1}(1+g) = (1-\delta) k_t + \frac{F(K_t, A_t N_t)}{A_t} - c_t
$$

Ryan's write-up:

Check for upper and lower case variables:

$$
V(k_t) = \max_{k+1, N_t} \{ u((1-\delta)) K_t + F(K_t, A_tN_t) - K_{t+1}, 1-N_t) + \beta V(k_{t+1}) \}
$$

$$
F(K_t, A_t, N_t) - K_tr_t - wA_tN_t
$$

1. $F_1(k, N) = r$
2. $F_N(k, N) = \frac{W}{A_t}$
3. $u_1(C, 1-N) = \beta u_1((1+g)C_0, 1-N)(\frac{1-\delta}{v} + (1+g))$
4. $u_1(C_0, 1-N)(W) = u_2(C_0, 1-N)$
5. $k_0(1+g) = (1-\delta)k_0 + F(k, N_t) - c_t$

(b) Show that if preferences are of the form: $u(C, 1-N) = \begin{cases} \frac{C^{1-\gamma}}{1-\gamma}h(1-N), \gamma > 0, \gamma \neq 1 \\ \log C + h(1-N), \gamma = 1 \end{cases}$ for some function $h$, then there will be a balanced growth path.

(c) Can we characterize the qualitative dynamics using a phase diagram in the same way that we did in the case of inelastic labor supply? For example, suppose $u(C, 1 - N) = \log C + h(1 - N)$, that we are on a balanced growth path and then there is an increase in the rate of depreciation $\delta$. Can you say what happens both upon impact of the shock and in the long run?

(d) Now suppose that $h$ is a constant function, so that labor is inelastically supplied, and suppose $\gamma > 1$. Show that we can summarize the equilibrium as a system of equations governing the evolution of consumption and capital per unit of effective labor: $c_t = C_t/A_t$ and $k_t = K_t/A_t$. Find the balanced growth path
levels of $c_t$ and $k_t$.

(e) Now suppose the economy is on the balanced growth path, and then there is a fall in the rate of technological change $g$. By analyzing the qualitative dynamics of the economy, discuss what happens to $c_t$ and $k_t$ at the time of the change and in the long run.

(f) For a marginal change in $g$, find an expression showing how the fraction of output saved on the balanced growth path changes. Does savings increase or decrease? Consider first a general production function, and then specialize to Cobb-Douglas production: $F(K, N) = K^\alpha N^{1-\alpha}$.

\pagebreak

2. At any date $t$, a consumer has $x_t$ units of a non-storable good. He can consume $c_t \in [0, x_t]$ of this stock, and plant the remaining $x_t - c_t$ units. He wants to maximize: $E \sum_{t=1}^\infty \beta^t \frac{c_t^{1-\gamma}}{1-\gamma}$ where $0 < \gamma < 1$ and $0 < \beta < 1$. Goods planted at date $t$ yield $A_t(x_t - c_t)$ as of the beginning of period $t + 1$, where $A_t$ is a sequence of i.i.d. random variables that take the values of $0 < A_h < 1/\beta$ with probability $\pi$ and $A_l \in (0, A_h)$ with probability $1 - \pi$.

(a) Formulate the consumer’s utility maximization problem in the space of shock contingent consumption sequences. Exactly what is this space? Exactly what does the expectations operator $E(\cdot)$ mean here? Be explicit.

$$
E_0 \Bigg[\sum_{t=0}^\infty \frac{\beta^t}{1- \gamma}(A_{t-1}S_{t-1} -S_t)^{1-\gamma} \Bigg]
$$


(b)  State the Bellman equation for this problem. It is easiest to have the consumer choose savings $s_t = x_t - c_t$. Argue that the relevant state variable for the problem is the cum-return wealth $A_{t-1}s_{t-1}$. Prove that the optimal value function is continuous, increasing, and concave in this state. How can you handle the unboundedness of the utility function?

$$
V(A_{t-1}, S_{t-1}) = \max_{s_t} \frac{(A_{t-1}s_{t-1} - s_t)^{1-\gamma}}{1-\gamma} + \beta[\pi V(A_h s_t) + (1-\pi)V(A_l s_t)]
$$

(c) Solve the Bellman equation and obtain the corresponding optimal policy function. (Hint: guess that the optimal function consists of saving a constant fraction
of wealth.)

(d)  How do you know that the consumption sequence generated by this policy function is the unique solution of the original sequence problem?

\pagebreak

3. This problem considers the computation of the optimal growth model. An infinitely lived representative household owns a stock of capital which it rents to firms. The household’s capital stock $K$ depreciates at rate $\delta$. Households do not value leisure and are endowed with one unit of time each period with which they can supply labor $N$ to
firms. They have standard time additive expected utility preferences with discount factor $\beta$ and period utility $u(c)$. Firms produce output according to the production
function $zF(K, N)$ where $z$ is the level of technology.

(a) First, write a computer program that solves the planners problem to determine the optimal allocation in the model. Set $\beta = 0.95$, $\delta = 0.1$, $z = 1$, $u(c) = c^{1-\gamma}/(1 - \gamma)$ with $\gamma = 2$, and $F(K, N) = K^{0.35}N^{0.65}$. Plot the optimal policy function for $K$ and the phase diagram with the $\Delta K = 0$ and $\Delta c = 0$ lines along with the saddle path (which is the decision rule $c(K)$).

(b) Re-do your calculations with $\gamma = 1.01$. What happens to the steady state? What happens to the saddle path? Interpret your answer.

(c) Now with $\gamma = 2$ assume that there is an unexpected permanent increase of 20% in total factor productivity, so now $z = 1.2$. What happens to the steady state levels of consumption and capital? Assuming the economy is initially in the steady state with $z = 1$, what happens to consumption and capital after the increase in $z$?