---
title: "ECON 703 - PS 2"
author: "Alex von Hafften^[I worked on this problem set with a study group of Michael Nattinger, Andrew Smith, Tyler Welch, and Ryan Mather. I also discussed problems with Emily Case, Sarah Bass, and Danny Edgel.]"
date: "8/24/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## (1) Consider the set $A = \{ \frac{1}{n} \}_{n \in \mathbb{N}}=\{1, \frac{1}{2}, \frac{1}{3}, \frac{1}{4}, ...\}$. Does there exist $S \subset \mathbb{R}$, such that the set of $S$'s limit points equals $A$?

No.

Proof: For the sake of a contradiction, assume that $\exists S \subset \mathbb{R}$ such that the set of $S$'s limit points, called $B$, equals $A= \{ \frac{1}{n} \}_{n \in \mathbb{N}}$.  For $\varepsilon > 0$, choose $n \in \mathbb{N}$ to be the smallest number to satisfy $\frac{1}{n} < \varepsilon$. Notice that there must exist an $s \in S$ such that $s \in B_{\frac{1}{4n}}(\frac{1}{2n})=(\frac{1}{2n} - \frac{1}{4n}, \frac{1}{2n} + \frac{1}{4n})$. Furthermore, $|s-0|<\frac{1}{2n} + \frac{1}{4n} < \frac{1}{n} < \varepsilon$, so 0 must be a limit point of $S$ and therefore $0 \in B$. However, $A \cap \{0\} = \emptyset$, so $A \neq B$. $\Rightarrow \Leftarrow$. No such $S \subset \mathbb{R}$ exists. $\square$

## (2) Prove that $f(x) = \cos x^2$ is not uniformly continuous on $\mathbb{R}$.

Proof: Let $\varepsilon = 1$.  Define $x = \sqrt{(2k+1)\pi}$ and $y = \sqrt{2k\pi}$ where $k \in \mathbb{N}$.  Notice that $f(x) = \cos x^2=-1$ and $f(y) = \cos y^2=1$, thus $|f(x) - f(y)| = |(-1) - 1| = 2 > \varepsilon$. Now consider 

\begin{align*}
|x-y| &= |\sqrt{(2k+1)\pi}-\sqrt{2k\pi}| \\
&= \frac{|(2k+1)\pi-2k\pi|}{|\sqrt{(2k+1)\pi}+\sqrt{2k\pi}|} \\
&= \frac{\pi}{|\sqrt{(2k+1)\pi}+\sqrt{2k\pi}|}
\end{align*}

As $k \to \infty$, $|x-y| \to 0 \implies |x-y|<\delta$ for any $\delta > 0$.  Thus, $f(x) = \cos x^2$ is not uniformly continuous on $\mathbb{R}$. $\square$

## (3) Show that if the function $f:\mathbb{R} \rightarrow \mathbb{R}_{++}$ is continuous on an interval $[a, b]$, where $\mathbb{R}_{++}=\{x\in\mathbb{R}|x>0\}$, then the reciprocal of this function ($\frac{1}{f}$) is bounded on this same interval.

Proof: By the extreme value theorem, we know that $f(x)$ attains its maximum and minimum on $x \in [a, b]$. Define $M_1 := \frac{1}{\sup f(x)}$ and $M_2 := \frac{1}{\inf f(x)}$ for $x \in [a, b]$. Notice that $\inf f(x) > 0$ because $f$ maps to $\mathbb{R}_{++}$. Thus, $\forall x \in [a, b]$, $0 < \frac{1}{M_2} \le f(x) \le \frac{1}{M_1} \implies M_1 \le \frac{1}{f(x)} \le M_2$. Thus, $\frac{1}{f(x)}$ is bounded on $[a, b]$. $\square$

## (4) $Bisection$ $method$. Let $f : [a, b] \rightarrow \mathbb{R}$ be a continuous function, $a < b, a, b \in \mathbb{R}$.  Assume that $f(a) < 0 < f(b)$. We want to show that $\exists c \in (a, b)$ such that $f(c) = 0$.  To do this, construct the following sequences:

## (I): Set $l_1 = a$, $u_1 = b$.

##(II): For each $n$, let $m_n = (l_n+u_n)/2$.

### - if $f(m_n) > 0$, then set $l_{n+1} = l_n, u_{n+1} = m_n$;
### - if $f(m_n) < 0$, then set $l_{n+1} = m_n, u_{n+1} = u_n$;
### - if $f(m_n) = 0$, then stop.
 
## Using what you have learned about the limits of real sequences, prove
 
## (a) Sequences $\{l_n\}$ and $\{u_n\}$ both converge.

Proof: To prove that $\{l_n\}$ and $\{u_n\}$ both converge, we show that $l_n < u_n$, $l_n \le l_{n+1}$, and $u_n \ge u_{n+1}$ $\forall n \in \{1, 2, ..., N\}$ by induction where $f(m_N) = 0$.  If these three conditions hold, both sequences converge by the monotone convergence theorem because $\{l_n\}$ is an increasing sequence bounded from above by $b$ and $\{u_n\}$ is a decreasing sequence bounded from below by $a$.

For the base step, $l_1 = a < b = u_1$ by assumption.

For the induction step, assume $l_n < u_n$. Furthermore, 

\begin{align*}
m_n - l_n = (l_n+u_n)/2 - l_n = (u_n - l_n)/2 >0 &\implies m_n > l_n \\
u_n - m_n = u_n - (l_n+u_n)/2 = (u_n - l_n)/2 >0 &\implies u_n > m_n
\end{align*}

Thus, $l_n < m_n < u_n$. If $f(m_n) > 0$, $l_{n+1} = l_n < m_n = u_{n+1} < u_n$. If $f(m_n) < 0$, $l_n < m_n = l_{n+1} < u_n = u_{n+1}$. If $f(m_n) = 0$, we stop and the sequences ends. Clearly, $\min\{l_n\}=l_1=a$ and $\max\{u_n\}=u_1=b$.  Hence, $\{l_n\}$ is an increasing sequence bounded from above by $b$ and $\{u_n\}$ is a decreasing sequence bounded from below by $a$, so both sequences converge. $\square$

## (b) Both sequences converge to the same limit, i.e. $\lim_{n \to \infty} l_n = \lim_{n \to \infty} u_n$. (Hint: Show that  $\{u_n - l_n\} \to 0$).

Proof: Notice $u_{n+1} - l_{n+1} = m_n - l_n = (l_n+u_n)/2 - l_n = (u_n - l_n)/2$ for $f(m_n) > 0$.  Similarly, for $f(m_n) < 0$, notice $u_{n+1} - l_{n+1} = u_n - m_n = u_n - (l_n+u_n)/2 = (u_n - l_n)/2$. So, if $u_{n+1}$ and $l_{n+1}$ exist, $u_{n+1} - l_{n+1} = (u_n - l_n)/2$.

I will now show by induction that $u_{n+1} - l_{n+1} = \frac{b - a}{2^n}$.  For the base step, $u_{2} - l_{2} = \frac{b - a}{2}$.  For the induction step, assume $u_{n+1} - l_{n+1} = \frac{b - a}{2^n}$:

\begin{align*}
u_{n+2} - l_{n+2} &= \frac{b - a}{2^{n+1}} \\
&= \frac{b - a}{2n}\frac{1}{2} \\
&= \frac{u_{n+1} - l_{n+1}}{2} \\
\end{align*}

For $\varepsilon > 0$, choose $N$ such that $\forall n > N$, $|\frac{b - a}{2^n}| < \varepsilon \implies \{u_n - l_n\} \to 0$. Since from (a), we know $u_n \to u$ and $l_n \to l$, this result implies that $u=l$. $\square$

## (c) Define the common limit of two sequences $c$ and show that $f(c)=0$.  (Hint: Use the continuity of $f$ and the fact that taking limits preserves weak inequalities).

Proof: Define $c$ as the limit of $u_n$ and $l_n$. Because $f$ is continuous, $f(u_n) \to f(c)$ and $f(u_n) \to f(c)$.

Now, I will show that $f(l_n) < 0 < f(u_n)$ for all $n \in \{1, ..., N\}$ where $f(m_N)=0$ using induction. For the base step, $f(l_1) =f(a) < 0 < f(b) = f(u_1)$. For the induction step, assume that $f(l_n) < 0 < f(u_n)$.  If $f(m_n) > 0$, then $f(l_n) = f(l_{n+1}) < 0 < f(m_n) = f(u_{n+1})$.  If $f(m_n) < 0$, then $f(l_{n+1}) = f(m_n) < 0 < f(u_n) = f(u_{n+1})$. Thus, $f(l_n) < 0 < f(u_n)$.  Since taking limits preserve weak inequalities: $f(l) \le 0 \le f(u) \implies f(c) \le 0 \le f(c) \implies f(c) = 0$. $\square$

## (5) Prove that at any time there are two antipodal points (diametrically opposite) on Earth that share the same temperature. (Hint: Use the Intermediate Value Theorem).

Proof: I will show that two antipodal points on any great circle, $C$, of the Earth share the same temperature.  A great circle of a sphere is the intersection of the sphere and a plane that passes through the center point of the sphere. (e.g., the Equator). Notice that if two antipodal points on any great circle of the Earth share the same temperature then any two arbitrary antipodal points on Earth must share the same temperature.  In addition, I assume that temperature is continuous when moving across the global and can be represented by a continuous function.

Let $x_0$ be the point that $C$ intersects the prime meridian.  If $C$ follows the prime meridian, let $x_0$ be Null Island (i.e. the point that the prime meridian intersects with the Equator). Construct a function $f(\theta):[0, 2\pi]\to \mathbb{R}$ that equals the temperature at a point on $C$ such that the angle between the point and $x_0$ is $\theta$ radians. Assume that $f$ is a continuous function.

Let $g(\theta) = f(\theta) - f(\theta + \pi)$.  Notice that $g(\theta)$ is the difference between the temperatures at antipodal points on $C$. As the difference of two continuous functions, $g(\theta)$ is also continuous.

If $g(0) = 0$, $f(0) - f(0 + \pi) = 0 \implies f(0) = f(\pi)$. Thus, the point $x_0$ and its antipodal point (i.e., the point at a $\pi$ radian angle from $x_0$)  share the same temperature.

If $g(0) > 0$, then 

\begin{align*}
f(0) - f(0 + \pi) > 0 & \implies 0 > f(\pi) - f(0) \\
& \implies 0 > f(\pi) - f(2\pi) \\
& \implies 0 > g(\pi)
\end{align*}

By the intermediate value theorem, there exists $\tilde{\theta} \in [0,\pi]$ such that $g(\tilde{\theta}) = 0 \implies f(\tilde{\theta}) = f(\tilde{\theta} + \pi)$.  The point at a $\tilde{\theta}$ radian angle from $x_0$ and its antipodal point (i.e., the point at a $\tilde{\theta} + \pi$ radian angle from $x_0$ along $C$) share the same temperature. 

If $g(0) < 0$, then 

\begin{align*}
f(0) - f(0 + \pi) < 0 & \implies 0 < f(\pi) - f(0) \\
& \implies 0 < f(\pi) - f(2\pi) \\
& \implies 0 < g(\pi)
\end{align*}

By the intermediate value theorem, there exists $\hat{\theta} \in [0,\pi]$ such that $g(\hat{\theta}) = 0 \implies f(\hat{\theta}) = f(\hat{\theta} + \pi)$.  The point at a $\hat{\theta}$ radian angle from $x_0$ and its antipodal point (i.e., the point at a $\hat{\theta} + \pi$ radian angle from $x_0$ along $C$) share the same temperature. $\square$


