---
title: "ECON 703 - PS 3"
author: "Alex von Hafften^[I worked on this problem set with a study group of Michael Nattinger, Andrew Smith, Tyler Welch, and Ryan Mather. I also discussed problems with Emily Case, Sarah Bass, and Danny Edgel.]"
date: "8/28/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## (1) Let $(X, d)$ be a nonempty complete metric space.  Suppose an operator $T: X \to X$ satisfies $d(T(x), T(y)) < d(x, y)$ for all $x \neq y, x, y \in X$.  Prove or disprove that $T$ has a fixed point.  Compare with the Contraction Mapping Theorem.

I disprove that such a $T$ has a fixed point using a counter example.

Proof: Consider the metric space $([1, \infty), d_E)$ and the operator $T(x)=x + \frac{1}{x}$. $T$ is an operator because if $x \ge 1$, then $x + \frac{1}{x} >x \ge 1$.

Consider $x \neq y, x, y \in [1, \infty)$. If $x>y \implies 0>\frac{1}{x} - \frac{1}{y}$, then\footnote{I show that $(x + \frac{1}{x}) - (y+\frac{1}{y}) > 0$ for $x>y\ge1$.  Rewrite $x=y+\varepsilon$ where $\varepsilon > 0$:

\begin{align*}
-(\frac{1}{x} - \frac{1}{y}) = \frac{1}{y} - \frac{1}{y+\varepsilon} = \frac{\varepsilon}{y(y+\varepsilon)} < \varepsilon = (y+\varepsilon) - y = x - y
\end{align*}

Because $y(y+\varepsilon) > 1$.}

\begin{align*}
d(x, y) &= |x - y|\\
&= x - y \\
&> x - y + (\frac{1}{x}- \frac{1}{y}) \\
&= (x + \frac{1}{x}) - (y+\frac{1}{y}) \\
&= |(x + \frac{1}{x}) - (y+\frac{1}{y})| \\
&= |T(x) - T(y)| \\
&= d(T(x), T(y))
\end{align*}

If $x<y$, switch $x$ for $y$ and $y$ for $x$ in the logic above. For the sake of a contradiction, assume that $T$ has a fixed point, $x^* \in [1, \infty)$ where $T(x^*) = x^*$. However, $T(x^*) = x^* +\frac{1}{x^*} > x^*$ $\Rightarrow \Leftarrow$.  Therefore, $T$ does not have a fixed point. $\square$

\pagebreak

## (2) Does there exist a countable set, which is compact?

Yes, there exists a countable compact set.

Proof: Consider $A = \{\frac{1}{n}: n \in \mathbb{N}\} \cup \{0\}$ and

\begin{align*}
f(x) = \begin{cases}
0,& n = 1 \\
\frac{1}{n-1},& n>1
\end{cases}
\end{align*}

Since $f$ is a one-to-one mapping between $\mathbb{N}$ and $A$, $A$ is countable.

Let $\mathcal{U}$ be an arbitrary open cover of $A$. $\exists U_{\lambda^*} \in \mathcal{U}$ such that $U_{\lambda^*} \supset B_\varepsilon(0)$ for some $\varepsilon > 0$. Let $\{a_n\} = 1/n$ for $n \in \mathbb{N}$. Since $a_n \to 0$, $\exists N$ such that, for all $n \ge N$, $a_n \in B_\varepsilon(0) \implies a_n \in U_{\lambda^*}$. Thus, we can construct a finite subcover of $A$ as the union of $U_{\lambda^*}$ and a finite number of $U_{\lambda_i} \in \mathcal{U}$, which each contain a $a_n \notin U_{\lambda^*}$ where $n=1, ..., N$. $\square$

## (3) Prove that the function $f(x) = \cos^2(x)e^{5-x-x^2}$ has a maximum on $\mathbb{R}$.

Proof: Using the extreme value theorem, I show that $f$ attains a maximum on $\mathbb{R}$ by (i) finding a compact set $C \subset \mathbb{R}$ where $\exists x \in C$ such that $f(x) > f(y) \forall y \in C^c$ and (ii) showing that $f$ is continuous on $\mathbb{R}$.  Define $g(x) = \cos^2(x)$, $h_1(x) = e^x$, $h_2(x)=5-x-x^2$, so that $f(x) = g(x)h_1(h_2(x))$.

For (i), define $C = [(-\sqrt{21}-1)/2, (\sqrt{21}-1)/2]$. As a closed interval of $\mathbb{R}$, $C$ is compact by the Heine-Borel theorem. For $0 \in C$, $f(0)=\cos^2(0)e^{5-0-0^2}=e^5>1$. Since $0 \le \cos^2(x) \le 1$, $f(x) \le h_1(h_2(x))$ for all $x \in \mathbb{R}$. Furthermore, if $h_2(x) < 0 \implies h_1(h_2(x))<1$. Because $h_2(0) = 5-0-0^2= 5$ and the quadratic roots of $h_2$ are $x = (\sqrt{21}-1)/2$ and $x = (-\sqrt{21}-1)/2$, $f(x) \le h_1(h_2(x)) < 1$ for all $x \in C^c$. Thus, the maximum of $f(x)$ on $\mathbb{R}$ must occur on $C$.

For (ii), since $g$, $h_1$, and $h_2$ are continuous functions on $\mathbb{R}$, $f$ is a continuous function on $\mathbb{R}$.\footnote{Proof that the products of two continuous functions is continuous.}

Thus, by the extreme value theorem, $f$ attains a maximum on $C$ and therefore on $\mathbb{R}$. $\square$

\pagebreak

## (4) Suppose you have two maps of Wisconsin: one large and one small.  You put the large one on top of the small one, so that the small one is completely covered by the large one.  Prove that it is possible to pierce the stack of those two maps in a way that the needle will go through exactly the same (geographical) points on both maps.

The intuition of the solution is that you repeatedly pierce the stack of maps each time moving closer and closer to the point on each map that represents the same geographical point.  First, you pierce a random place on the stack of maps.  If the holes in each map represent the same geographical point and we're done. If not, let $a$ be the geographical point at the hole on the larger map.  Then pierce the stack of maps where $a$ is represented on the smaller map.  Repeat this process until the holes represent the same geographical point.

For example, say the larger map and the small map are stack on top of each such that north is parallel and Madison on the larger map is right above Madison on the smaller map.  If you pierce the map at Milwaukee on the smaller map, the large map would be pierced somewhere on I-94, say Johnson Creek. Then you locate Johnson Creek on the small map and pierce the map stack.  The new hole in the large map would be closer to Madison along I-94, say Goose Drumlins State Natural Area.  If you repeatedly pierce the map stack in such a way, you get closer and closer to Madison on both maps.

Proof: Define $A \subset \mathbb{R}^2$ as the closed set of points on the smaller map that are on or within Wisconsin's borders. Similarly, define $B \subset \mathbb{R}^2$ as the closed set of points on the larger map that are on or within Wisconsin's borders. Notice that the metric space $(A, d_E)$ is complete because $A \subset \mathbb{R}^2$ is closed. 

Define mapping $f: A \to B$ such that $f(x)$ is the point on the larger map would be pierce if $x$ on the smaller map is pierced.  Define mapping $g: B \to A$ such that $x$ and $g(x)$ represent the same geographical points.  Thus, define $T = f \circ g : A \to A$. Intuitively, $T(x)$ is the point on the smaller map representing the same geographical point as the hole on the larger map when $x$ on the small map is pierced.

For $x, y \in A, x \neq y$, $d_E(x, y) = d_E(f(x), f(y))$ because $x$ and $y$ sit right below $f(x)$ and $f(y)$. For $w, z \in B, w \neq z$, $d_E(w, z) = \beta d_E(g(w), g(z))$  where $\beta < 1$ is the ratio of the miles per inch on the larger map to the miles per inch on the smaller map. $w$ and $g(w)$ represent the same geographical point and $z$ and $g(z)$ represent the same geographical point  with $w$ and $z$ on the larger map and $g(w)$ and $g(z)$ on the smaller map.  Thus, $d_E(x, y) = d_E(f(x), f(y)) = \beta d_E(g(f(x)), g(f(y))) = \beta d_E(T(x), T(y))$, so $T$ is a contraction with modulus $\beta < 1$.  Thus, $T$ has a fixed point where $T(x^*) = x^*$. You can pierce the stack of maps at $x^*$ on the smaller map and pierce the same geographical point on the larger map.  $\square$

\pagebreak

## (5) Consider the set $X = \{-1, 0, 1\}$ and the space of all functions on $X$, $F_X = \{f: X \to \mathbb{R}\}$.

## (a) Show that $F_X$ is a vector space.

Proof: To show that $X$ is a vector space, I satisfy the eight properties of vector space with $X$:

* Let $a, b, c \in F_X$. $\forall x \in X$, $(a(x)+b(x))+c(x) = a(x)+(b(x)+c(x))$.

* Let $a, b \in F_X$. $\forall x \in X$, $a(x)+b(x) = b(x)+a(x)$.

* Let $a, \bar{0} \in F_X$ where $\bar{0}(x)=0$ $\forall x \in X$, so $a(x)+\bar{0}(x) = \bar{0}(x)+a(x) = a(x)$.

* Let $a, (-a) \in F_X$ where $(-a)(x) = -a(x)$ $\forall x \in X$, so $a(x) + (-a)(x) = a(x) -a(x) = 0 = \bar{0}(x)$.

* Let $a, b \in F_X$ and $\alpha \in \mathbb{R}$. $\forall x \in X$, $\alpha ( a(x) + b(x))=\alpha a(x) + \alpha b(x)$.

* Let $a \in F_X$ and $\alpha, \beta \in \mathbb{R}$. $\forall x \in X$, $(\alpha + \beta)  a(x) =\alpha a(x) +  \beta  a(x)$.

* Let $a \in F_X$ and $\alpha, \beta \in \mathbb{R}$. $\forall x \in X$, $(\alpha * \beta)  a(x) =\alpha ( \beta*  a(x))$.

* Let $a \in F_X$. $\forall x \in X$, $1 *  a(x) = a(x)$. $\square$

## (b) Show that the operator $T: F_X \to F_X$ defined by $T(f)(x)=f(x^2), x \in \{-1, 0, 1\}$ is linear.

An arbitrary $f \in F_X$ is

\begin{align*}
f(x) = \begin{cases} 
      a & x = -1 \\
      b & x = 0 \\
      c & x = 1 
   \end{cases}
\end{align*}

where $a, b, c \in \mathbb{R}$.  Applying $T$ to $f$,

\begin{align*}
T(f)(x) = f(x^2) = \begin{cases} 
      a & x = \{-1, 1\} \\
      b & x = 0.
   \end{cases}
\end{align*}

Proof: Let $a, b \in F_X$ and $\alpha, \beta \in \mathbb{R}$. $\exists c \in F_X$, such that $c(x) = \alpha a(x) + \beta b(x)$ $\forall x \in X$.  Apply $T$ to $c(x)$:

\begin{align*}
T(c)(x) &= c(x^2) \\
&= \alpha a(x^2) + \beta b(x^2) \\
&= \alpha T(a)(x) + \beta T(b)(x)
\end{align*}

Thus, $T$ is linear. $\square$

## (c) Calculate ker $T$, Im $T$, and rank $T$.

ker $T = \{f \in F_X | T(f) = \bar{0}\}= \{f \in F_X | f(0)=f(1)=0\}$.

Im $T = \{T(f) | f \in F_X\}= \{ f(x^2)|f \in F_X\} = \{(a, b)| a, b \in \mathbb{R}\} = \mathbb{R}^2$.

rank $T=$ dim $($Im $T)=$ dim $(\mathbb{R}^2) = 2$.

\pagebreak

## (6) Consider the following system of linear equations

\begin{align}
x_1 + x_2+2x_3+x_4 &= 0 \\
3x_1 - x_2 + x_3 - x_4 &= 0 \\
5x_1-3x_2 -3x_4 &= 0
\end{align}

## Let $X$ be the set of $\{x_1, x_2, x_3, x_4\}$ which satisfy the system of equations.

## (a) Show that $X$ is a vector space.

Proof: First I find a basis for $X$:

\begin{align}
(3) \implies 5x_1 &= 3x_2+3x_4
\end{align}

\begin{align*}
(3) & (4) \implies \frac{3}{5}(x_2 + x_4) + x_2+2x_3+x_4 &= 0\\
2x_3 &= -\frac{8}{5}(x_2 + x_4)\\
5x_3 &= -4(x_2 + x_4)
\end{align*}

Letting $x_2 = a$ and $x_3 = b$, all elements of $X$ can be represented by 

\begin{align*}
y &= \begin{bmatrix}
           3(a + b) \\
           5a \\
           -4(a + b) \\
           5b
         \end{bmatrix} \\
 &= a \begin{bmatrix}
           3 \\
           5 \\
           -4 \\
           0
         \end{bmatrix}
+ b \begin{bmatrix}
           3 \\
           0 \\
           -4 \\
           5
         \end{bmatrix}\\
 &=a \vec{u} + b \vec{v}
\end{align*}

Thus, $\{\vec{u}, \vec{v}\}$ forms a basis for $X$ because they span $X$ and they are linearly independent. 

For $x, y, z \in X$, $\exists o, p, q, r, s, t \in \mathbb{R}$ such that $x = o \vec{u} + p \vec{v}$, $y = q \vec{u} + r \vec{v}$, and $y = s \vec{u} + t \vec{v}$.  Vector spaces have eight properties:

* $(x+y)+z = (o \vec{u} + p \vec{v}+ q \vec{u} + r \vec{v}) + s \vec{u} + t \vec{v}  = o \vec{u} + p \vec{v}+ (q \vec{u} + r \vec{v} + s \vec{u} + t \vec{v}) = x+(y+z)$.

* $x+y = o \vec{u} + p \vec{v}+ q \vec{u} + r \vec{v} = q \vec{u} + r \vec{v} + o \vec{u} + p \vec{v} = y+x$.

* Let $\bar{0} \in X$ be $0 * \vec{u} + 0 * \vec{v}$. $x+\bar{0} = o \vec{u} + p \vec{v} + 0 * \vec{u} + 0 * \vec{v} =(o+0) \vec{u} + (p+) \vec{v}=o \vec{u} + p \vec{v}=x$.

* Let $(-x)= (-o) \vec{u} + (-p) \vec{v}$. $x + (-x) = o \vec{u} + p \vec{v}+(-o) \vec{u} + (-p) \vec{v} = (o-o) \vec{u} + (p-p) \vec{v} = 0 * \vec{u} + 0 * \vec{v} = \bar{0}$.

* Let $\alpha \in \mathbb{R}$. $\alpha(x+y) = \alpha(o \vec{u} + p \vec{v}+ q \vec{u} + r \vec{v}) = \alpha(o \vec{u} + p \vec{v})+ \alpha(q \vec{u} + r \vec{v}) = \alpha x + \alpha y$.

* Let $\alpha, \beta \in \mathbb{R}$. $(\alpha + \beta) x = (\alpha + \beta) (o \vec{u} + p \vec{v}) = \alpha (o \vec{u} + p \vec{v}) + \beta (o \vec{u} + p \vec{v}) = \alpha x + \beta y$.

* Let $\alpha, \beta \in \mathbb{R}$. $(\alpha * \beta) x = (\alpha * \beta) (o \vec{u} + p \vec{v}) = \alpha  (\beta (o \vec{u} + p \vec{v})) =  \alpha  (\beta x)$.

* $1 * x = 1 * (o \vec{u} + p \vec{v}) = 1 * o \vec{u} + 1 * p \vec{v} = o \vec{u} + p \vec{v} = x$.

Thus, $X$ is a vector space. $\square$

## (b) Calculate dim $X$.

From (a), we found that $\{(3, 5, -4, 0), (3, 0, -4, 5)\}$ form a basis for $X$.  Since the dimension of $X$ is the cardinality of a basis for $X$, dim $X = 2$.
