---
title: "ECON 703 - PS 7"
author: "Alex von Hafften^[I worked on this problem set with a study group of Michael Nattinger, Andrew Smith, and Ryan Mather. I also discussed problems with Emily Case, Sarah Bass, and Danny Edgel.]"
date: "10/7/2020"
output: pdf_document
header-includes:
- \newcommand{\N}{\mathbb{N}}
- \newcommand{\Z}{\mathbb{Z}}
- \newcommand{\R}{\mathbb{R}}
- \newcommand{\Q}{\mathbb{Q}}
- \newcommand{\co}{\text{co}}
- \newcommand{\cl}{\text{cl}}
- \newcommand{\hyp}{\text{hyp}}
- \usepackage{bm}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

(1) Let $X \subset \R^n$ be a convex set, and $\lambda_1, ..., \lambda_k \ge 0$ with $\sum_{i=1}^k \lambda_i = 1$. Prove that if $x_1, ..., x_k \in X$, then $\sum_{i=1}^k \lambda_i x_i \in X$.

Proof (by induction): For the base step, choose $\lambda_1, \lambda_2 \ge 0$ such that $\lambda_1 + \lambda_2 = 1$.  For any $x_1, x_2 \in X \subset \R^n$, $\lambda_1 x_1 + \lambda_2 x_2 \in X$ because $X$ is convex.  For some $k$, assume that $\sum_{i=1}^k \lambda_i x_i \in X$ for $x_1, ..., x_k \in X$ with $\lambda_1, ..., \lambda_k \ge 0$ and $\sum_{i=1}^k \lambda_i = 1$. Consider $k+1$. Choose $\lambda'_1, ..., \lambda'_{k+1} \ge 0$ such that $\sum_{i=1}^{k+1} \lambda'_i = 1$:

$$
\sum_{i=1}^{k+1} \lambda'_i x_i = 
\sum_{i=1}^{k} \lambda'_i x_i+\lambda'_{k+1} x_{k+1}= 
\Bigg( \sum_{i=1}^{k} \lambda'_i \Bigg) \sum_{i=1}^{k} \Bigg( \frac{\lambda'_i}{\sum_{i=1}^{k} \lambda'_i} x_i \Bigg)+\lambda'_{k+1} x_{k+1}
$$

By the induction hypothesis, $y:=\sum_{i=1}^{k} \Bigg( \frac{\lambda'_i}{\sum_{i=1}^{k} \lambda'_i} x_i \Bigg) \in X$ because $\sum_{i=1}^{k}\frac{\lambda'_i}{\sum_{i=1}^{k} \lambda'_i} = 1$. Thus,

$$
\sum_{i=1}^{k+1} \lambda'_i x_i = \Bigg( \sum_{i=1}^{k} \lambda'_i \Bigg) y + \lambda'_{k+1} x_{k+1}
$$

By the definition of convexity, $\sum_{i=1}^{k+1} \lambda'_i x_i \in X$ because $\sum_{i=1}^{k} \lambda'_i + \lambda'_{k+1} = 1$. $\square$

(2) The sum $\sum_{i=1}^k \lambda_i x_i$ defined in Problem (1) is called a convex combination. The convex hull of a set $S$, denoted by $\co(S)$, is the intersection of all convex sets which contain $S$. Prove that the set of all convex combinations of the elements of $S$ is exactly $\co(S)$.

Proof: We show that an arbitrary convex combination of elements of $S$ is in $\co(S)$ and an arbitrary point in $\co(S)$ can be represented by a convex combination of elements of $S$.  First, notice that $S \subset \co(S)$ and $\co(S)$ is convex because it is the intersection of convex sets. 

Consider an arbitrary convex combination of elements of $S$, $\sum_{i=1}^k \lambda_i s_i$ with $s_1, ..., s_k \in S$. Since $s_i \in S$, $s_i \in \co(S)$ for $i \in \{1, ..., k\}$.  Since $\co(S)$ is convex, $\sum_{i=1}^k \lambda_i s_i \in \co(S)$.

Consider $x \in \co(S)$. Assume for the sake of a contradiction that $x$ cannot be represented as a convex combination of elements of $S$.  Then there exists a convex set $Y$ such that $S \subset Y$ and $x \notin Y$.  This is a contradiction because $\co(S)$ is the intersection of all convex sets which contain $S$. Thus, $x$ can be represented as a convex combination of elements of $S$. $\square$

\pagebreak

(3) For any set $X \subset \R^n$, let its closure be $\cl X = X \cup \{$all limit points of $X\}$. Show that the closure of a convex set is convex.

Proof: Let $X$ be a convex set. Choose two points $x, y \cl X$. Thus, there exists sequences $\{x_n\}, \{y_n\} \in X$ such that $\{x_n\} \to x$ and $\{y_n\} \to y$.  Since $X$ is convex, $\lambda x_n + (1-\lambda) y_n \in X$ for all $n$ with $\lambda \in [0, 1]$. Because $\cl X$ contains all limit points of $X$, $\lambda x + (1- \lambda)y = \lim_{n \to \infty} (\lambda x_n + (1-\lambda) y_n) \in \cl X$. $\square$

(4) The function $f: X \to \R$, where $X$ is a convex set in $\R^n$, is concave if $\forall \lambda \in [0,1], x', x'' \in X$, $f((1-\lambda)x' + \lambda x'') \ge (1-\lambda)f(x')+\lambda f(x'')$. Given a function $f: X \to \R$, its hypograph is the set of points $(y, x)$ lying on or below the graph of the function: $\hyp f =\{(y,x) \in \R^{n+1}| x \in X, y \le f(x)\}$. Show that the function $f$ is concave if and only if its hypograph is a convex set.

Proof: Assume a function $f: X \to \R$ is concave where $X$ is a convex set in $\R^n$.  To show that its hypograph is a convex set, we need to show that, for any $\lambda \in [0, 1]$ and $(y', x'), (y'', x'') \in \hyp f$, $\lambda (y', x') + (1-\lambda) (y'', x'') = (\lambda y' + (1-\lambda)y'', \lambda x' + (1-\lambda)x'')  \in \hyp f$.  First, notice that since $X$ is convex, $\lambda x' + (1-\lambda) x'' \in X$. Since $f$ is concave, $f(\lambda x' + (1-\lambda)x'') \ge (1-\lambda)f(x')+\lambda f(x'') \ge (1-\lambda)y'+\lambda y''$. Thus, $\lambda (y', x') + (1-\lambda) (y'', x'') \in \hyp f$.

Assume that the hypograph of a function $f: X \to \R$ is convex.  Choose $(x', y'), (x'', y'') \in \hyp f$. To show that $X$ is convex, we need to show that, for any $\lambda \in [0, 1]$, $f((1-\lambda)x' + \lambda x'') \ge (1-\lambda)f(x')+\lambda f(x'')$.  Since $\hyp f$ is convex, we know that $\lambda f(x') + (1-\lambda)f(x'') \le \lambda y' + (1-\lambda)y'' \le f((1-\lambda)x' + \lambda x'')$. Thus, $f$ is concave.

(5) Let $X$ and $Y$ be disjoint, closed, and convex sets in $\R^n$, one of which is compact. Show that there exists a hyperplane $H(p, \alpha)$ that strictly separates $X$ and $Y$.

Proof: Let $X$ and $Y$ be disjoint, closed, and convex sets in $\R^n$ and $X$ be compact. Let $Z := X-Y = \{z \in \R^n | z=x-y$ for some $x \in X, y \in Y\}$.  The set $Z$ is convex and $\bar{0} \notin Z$ because $X \cap Y = \emptyset$.  By the theorem on slide 6 of the lecture 14 slides, there exists a hyperplane $H(p, \beta)$ that strictly separates $Z$ and $\{\bar{0}\}$.  Thus, for all $z \in Z, x \in X, y \in Y$,

$$
p \cdot \bar{0} < p \cdot z
\implies 0 < p \cdot (x-y)
\implies p \cdot y < p \cdot x 
$$

Pick $x' \in X$. Since $p \cdot y$ is bounded from above by $p \cdot x'$ for all $y \in Y$, define $\beta' := \sup_{y \in Y} \{p \cdot y\} \in \R$. Define $f:X \to \R$ as $f(x) = p \cdot x$.  Since $f$ is continuous and X is compact, $f$ attains its minimum on $X$, by the extreme value theorem.  Define $\beta'' := \min_{x \in X}\{f(x)\} = \min_{x \in X} \{p \cdot x\} \in \R$.  Since $X$ and $Y$ are disjoint, $\beta'$ is strictly less than $\beta''$. By the denseness of rational numbers, there exists a $\beta^* \in \Q$ such that $\beta'< \beta^* < \beta''$. Therefore, for all $x \in X$ and $y \in Y$:

$$
p \cdot y \le \sup_{y \in Y} p \cdot y = \beta'< \beta^*< \beta'' = \min_{x \in X} \{p \cdot x\} \le p \cdot x 
$$

Thus, $X$ and $Y$ are strictly separated by $H(p, \beta^*)$. $\square$

\pagebreak

(6) Call a vector $\pi \in \R^n$ a probability vector if $\sum_{i=1}^n \pi_i = 1$ and $\pi_i \ge 0$ for all $i=1, ..., n$. Interpretation is that there are $n$ states of the world and $\pi_i$ is the probability that state $i$ occurs. Suppose that Alice and Bob each have a set of probability distributions ($\Pi_A$ and $\Pi_B$) which are nonempty, convex, and compact.  They propose bids on each state of the world.  A vector $x = (x_1, ..., x_n) \in \R^n$, where $x_i$ denotes the net transfer Alice receives from Bob in state $i$, is called a trade (Thus, $-x$ is the net transfer Bob receives in each state of the world.) A trade is agreeable if $\inf_{\pi \in \Pi_A}\sum_{i=1}^n \pi_i x_i > 0$ and $\inf_{\pi \in \Pi_B}\sum_{i=1}^n \pi_i (-x_i) > 0$. The above means that both Alice and Bob expect to strictly gain from the trade. Prove that there exists an agreeable trade iff there is no common prior (i.e., $\Pi_A \cap \Pi_B = \emptyset$).



