---
title: "ECON 710A - Problem Set 6"
author: "Alex von Hafften^[I worked on this problem set with a study group of Michael Nattinger, Andrew Smith, and Ryan Mather. I also discussed problems with Sarah Bass, Emily Case, Danny Edgel, and Katherine Kwok.]"
date: "3/8/2021"
output: pdf_document
header-includes:
- \newcommand{\N}{\mathbb{N}}
- \newcommand{\Z}{\mathbb{Z}}
- \newcommand{\R}{\mathbb{R}}
- \newcommand{\Q}{\mathbb{Q}}
- \newcommand{\var}{\text{var}}
- \newcommand{\rank}{\text{rank}}
- \newcommand{\twiddle}{\tilde}
- \newcommand{\Lfn}{\mathcal{L}}
- \usepackage{bm}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(knitr)
```

1. Consider a random effects model with an intercept only: $Y_{it} = \mu_0 + \alpha_i + \varepsilon_{it}$ $(i=1, ..., n, t=1, ..., T_i)$ with $\varepsilon_i = (\varepsilon_{i1}, ..., \varepsilon_{iT_i})'$ independent across $i$, $E[\alpha_i]=E[\varepsilon_i]=0$, and

$$
Var \begin{pmatrix} \alpha_i \\ \varepsilon_i \end{pmatrix}
= \begin{bmatrix} \sigma_{\alpha}^2 & 0 \\ 0 & \sigma^2 I_{T_i} \end{bmatrix}
\text{ where }
\sigma^2 > 0
$$

(i) Argue that the OLS estimator of $\mu_0$ (the sample average), can be represented as $\hat{\mu}_{OLS} = \frac{\sum_{i=1}^n 1_i' Y_i}{\sum_{i=1}^n 1_i' 1_i}$ where $1_i = (1, ..., 1)' \in \R^{T_i}$ and $Y_i = (Y_{i1}, ..., Y_{iT_i})'$.

...

(ii) For a non-random instrument $Z_i \in \R^{T_i}$, consider the IV estimator $\hat{\mu}_{IV} = \frac{\sum_{i=1}^n Z_i' Y_i}{\sum_{i=1}^n Z_i' 1_i}$. Show that $Var(\hat{\mu}_{IV}) = \frac{\sum_{i=1}^n Z_i' \Omega_i Z_i}{(\sum_{i=1}^n Z_i' 1_i)^2}$ for some $\Omega_i = \Omega_i (\sigma_\alpha^2, \sigma^2, T_i)$ and find $\Omega_i$.

...

(iii) Show that $Var(\hat{\mu}_{IV}) \ge (\sum_{i=1}^n 1_i' \Omega_i^{-1} 1_i)^{-1}$ and find an instrument $\tilde{Z}_i$ (possibly depending on $\Omega_i$) such that $Var(\frac{\sum_{i=1}^n \tilde{Z}_i' y_i}{\sum_{i=1}^n \tilde{Z}_i' 1_i}) = (\sum_{i=1}^n 1_i' \Omega_i^{-1} 1_i)^{-1}$.

...

(iv) The IV estimator that uses $\tilde{Z}_i$ is often referred to as generalized least squares (GLS) and it is (weakly) more efficient than the OLS estimator. Is GLS strictly more efficient than OLS if $T_i=T$ for all $i$?

...

(v) Show that $\hat{\sigma}_i^2 = \frac{1}{T_i - 1}\sum_{t=1}^{T_i} (Y_{it} - \bar{Y}_i)^2$ where $\bar{Y}_i = \frac{1}{T_i} \sum_{i=1}^{T_i}  Y_{it}$ has expectation equal to $\sigma^2$ and argue (informally) that $\hat{\sigma}^2 = \frac{1}{n} \sum_{i=1}^n \hat{\sigma_i}^2$ is consistent for $\sigma^2$ as $n \to \infty$.

...

(vi) Show that $\hat{\sigma}_{\alpha, i} (\mu) = \frac{1}{T_i} \sum_{t=1}^{T_i} (Y_{it} - \mu)^2-\hat{\sigma}_i^2$ has expectation equal to $\sigma_\alpha^2$ when $\mu=\mu_0$ and argue (informally) that $\hat{\sigma}_{\alpha}^2 = \frac{1}{n} \sum_{i=1}^n \hat{\sigma}_{\alpha, i}^2(\hat{\mu}_{OLS})$ is consistent for $\hat{\sigma}_\alpha^2$ as $n\to \infty$.

...

(vii) If we let $\hat{\Omega}_i = \Omega_i(\hat{\sigma}_\alpha^2, \hat{\sigma}^2, T_i)$ and use this to construct a feasible version of $\tilde{Z_i}$, then we obtain the feasible GLS estimator. In the panel data context, this estimator is also referred to as the random effects estimator. The previous arguments imply that $\sqrt{n}\hat{\mu}_{FGLS}$ and $\sqrt{n}\hat{\mu}_{GLS}$ has the same asymptotic variances as $n\to\infty$. Propose a variance estimator $\hat{V}$ for which you expect (based on the previous questions) that $\hat{V}^{-1/2}(\hat{\mu}_{FGLS} - \mu_0)\to_d N(0,1)$.

...

\pagebreak

2. Consider a fixed effects regression model $Y_{it} = X_{it} \beta_0 + \alpha_i + \varepsilon_{it}$ ($i=1, ..., n, t=1, ..., T$) where data is independent across $i$, $X_{it}$ is independent of $X_{is}$ for $s \neq t$ with $E[X_{it}] = 0$ and $E[X_{it}^2] = \sigma_x^2$ for all $t$, and strict exogeneity fails since $E[X_{is} \varepsilon_{it}] = \delta \sigma_x^21\{s = t+1\}$. Such failure can hapen if the regressor is a response to a previous shock, e.g., $X_{it} = \delta \varepsilon_{i, t-1} + u_{it}$ for $t \ge 1$ and $\varepsilon_{it}$ independent of $u_{it}$.

(i) Derive asymptotic biases of the fixed effects estimator and the first differences estimator as $n \to \infty$. \footnote{You may use without proof that $\hat{\beta}_{FE} \to_p \beta_0 + \frac{\sum_{t=1}^T (X_{i,t} - \bar{X}) \varepsilon_{i,t}}{\sum_{t=1}^T (X_{i,t} - \bar{X})^2}$ and $\hat{\beta}_{FD} \to_p \beta_0 + \frac{\sum_{t=1}^T (X_{i,t} - X_{i,t-1}) (\varepsilon_{it}-\varepsilon_{it-1})}{\sum_{t=1}^T (X_{i,t} - X_{i,t-1})^2}$}

...

(ii) Is there a value of $T$ so that the two asymptotic biases are identical?

...

\pagebreak

3. Consider panel data $\{\{(Y_{it},X_{it})'\}^T_{t=1}\}^n_{i=1}$ generated by the model $Y_{it}=X_{it}\beta_0+\delta_t+\alpha_i+\varepsilon_{it}$, where $\{(Y_{it},X_{it})'\}^T_{t=1}$ is i.i.d. across $i$, $T= 4$, and $(X_{i1},...,X_{i4})' = (0,0,1,1)' \cdot 1\{\alpha_i> .6\}$. The error terms has an autoregressive structure $\varepsilon_{it}=\phi \varepsilon_{i,t-1}+u_{it}$ for $t \ge 1$, and $\alpha_i$, $\varepsilon_{i0}$, and $u_{i1},...,u_{i4}$ are i.i.d. $N(0,1)$. The parameters take the values $\beta_0=\delta_2=\delta_3=\delta_4= 1$ while $\delta_1$ is normalized to zero and omitted from the model. We will vary the autoregressive parameter in $\{0,0.8\}$ and consider sample sizes $n\in\{40,70,100\}$.

(i) In a statistical software of your choice, generate data according to (1), estimate $(\beta_0,\delta_2,\delta_3,\delta_4)$ using the FE estimator, and calculate both a heteroskedasticity robust variance estimate and a cluster robust variance estimate where the clustering is at the individual level. Use these variance estimators to construct two different 95% confidence intervals for $\beta_0$. Additionally, calculate the OLS estimator of the regression coefficients in the (misspecified) common intercepts model $Y_{it} = \alpha + X_{it} \beta_0 + \delta_t + \varepsilon_{it}$.

...

(ii) Across 10000 simulated repetitions of the above, report the mean of the two point estimators for $\beta_0$ (OLS and FE) and the coverage rate for the two confidence intervals that rely on different variance estimators.

...

(iii) Discuss the results and relate them to the theory presented in lecture.

...

