---
title: "ECON 711B - Problem Set 3"
author: "Alex von Hafften^[I worked on this problem set with a study group of Michael Nattinger, Andrew Smith, Tyler Welch, and Ryan Mather. I also discussed problems with Emily Case, Sarah Bass, and Danny Edgel.]"
date: "11/15/2020"
output: pdf_document
header-includes:
- \newcommand{\N}{\mathbb{N}}
- \newcommand{\Z}{\mathbb{Z}}
- \newcommand{\R}{\mathbb{R}}
- \newcommand{\Q}{\mathbb{Q}}
- \newcommand{\Lf}{\mathcal{L}}
- \usepackage{bm}
- \usepackage{bbm}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
```

1. (Arms race with market power) Two (expected payoff maximizing) gangs are competing in an arms race. Each of them likes having more weapons $w_i$ but dislikes having a different amount than the other agent. Obtaining weapons is costly, with the price of weapons increasing in the average quantity of weapons purchased.  The price of weapons is $P(\bar{w}) = \rho + \alpha \bar{w}$ where $\bar{w}$ is the average amount of weapons purchased. Each gang's payoff is $u_i(w_i, w_j) = \gamma w_i - \beta (w_i - w_j)^2 - P(\bar{w}) w_i$. All parameters $\alpha, \beta, \gamma$ and $\rho$ are strictly positive, and $\gamma > \rho$.

(a) Explain the economic intuition of the assumption that $\gamma > \rho$. What does this assumption guarantee?

Substituting in the price function and $\bar{w} = \frac{w_i + w_j}{2}$ into the payoff function:

\begin{align*}
u_i(w_i, w_j) 
&= \gamma w_i - \beta (w_i - w_j)^2 - (\rho + \alpha (w_i + w_j)/2) w_i \\
&= (\gamma - \rho) w_i - \beta (w_i - w_j)^2 -  (\alpha/2)w_i^2 - (\alpha/2) w_i w_j
\end{align*}

Assuming that $\gamma > \rho$ insures that there is positive payoff for a gang to buy a positive amount of weapons. If $\gamma \le \rho$, neither gang would buy any weapons; it pushes us away from a corner solution.

(b) Under what condition(s) is this game supermodular?

The game is supermodular if payoffs $u_i(w_i, w_j)$ has increasing differences for $i$ and $j$.

$$
\frac{\partial u_i}{\partial w_i} = (\gamma - \rho) - 2\beta (w_i - w_j)  - \alpha w_i - (\alpha/2) w_j 
$$

$$
\frac{\partial^2 u_i}{\partial w_i \partial w_j} = 2\beta - \alpha/2
$$

If $4\beta \ge \alpha$, the game is supermodular.

(c) Find the symmetric pure-strategy Nash equilibrium.

FOC [$w_i$]:

$$
0 = (\gamma - \rho) - 2\beta (w_i^* - w_j)  - \alpha w_i^* - (\alpha/2) w_j \\
\implies  w_i^* = \frac{\gamma - \rho}{\alpha +2\beta} + \frac{4\beta - \alpha}{2\alpha +4\beta} w_j \\
$$
\pagebreak

For a symmetric pure-strategy Nash equilibrium $w_j = w_i^*$:

$$
w_i^* = \frac{\gamma - \rho}{\alpha +2\beta} + \frac{4\beta - \alpha}{2\alpha +4\beta} w_i^* \\
\implies w_i^* = \frac{2\gamma - 2\rho}{3\alpha} \\
$$

Thus, the symmetric pure-strategy Nash equilibrium is both gangs buying $\frac{2\gamma - 2\rho}{3\alpha }$ weapons.

(d) In the Nash equilibrium you found in part (c), how does the equilibrium quantity of weapons change with each parameter? Provide intuition for each effect.

\begin{align*}
\uparrow \gamma &\to \uparrow w_i^* \\
\uparrow \rho &\to \downarrow w_i^* \\
\uparrow \alpha &\to \downarrow w_i^* \\
\uparrow \beta &\to \text{ no change in } w_i^* \\
\end{align*}

$\gamma$ is the inherent marginal benefit to the gang of additional weapons (maybe it's the additional revenue associated with additional weapons). If weapons are inherently more valuable to the gang, they'll consume more.

$\rho$ is the reservation price for the weapon supplier.  It is the intercept of the supply curve. If the reservation price for the weapon supplier is higher, the gang will buy fewer weapons because they would be more expensive.

$\alpha$ measures the market power of the weapons supplier.  It is twice the slope of the supply curve.  If the weapon supplier have more market power, the gang will buy fewer weapons because they would be more expensive.

$\beta$ measures the disutility associated with having a different amount of weapons as the other gang.  In the symmetric equilibrium, the gangs choose the same amount of weapons, so the disutility of having different amounts of weapons does not factor in.

(e) Does there exist an equilibrium in which one or both gangs choose to have no weapons? If so, find such an equilibrium; if not, show why not.

Assume $w_j = 0$. 

$$
w_i^* = \frac{\gamma - \rho}{\alpha +2\beta} + \frac{4\beta - \alpha}{2\alpha +4\beta} (0) \\
\implies w_i^* = \frac{\gamma - \rho}{2\beta - \alpha}
$$

We know that $\frac{\gamma - \rho}{2\beta - \alpha} \neq 0$ because $\gamma - \rho > 0$, so both gangs having no weapons is not an equilibrium.  If $2\beta > \alpha$, $\frac{\gamma - \rho}{2\beta - \alpha} > 0$.  Now let us determine whether $w_i^* = 0$ is a best response to $w_j = \frac{\gamma - \rho}{2\beta - \alpha}$:

$$
w_i^* = \frac{\gamma - \rho}{\alpha +2\beta} + \frac{4\beta - \alpha}{2\alpha +4\beta} \frac{\gamma - \rho}{2\beta - \alpha} \\
\implies w_i^* = \frac{\gamma - \rho}{\alpha +2\beta} + \frac{4\beta - \alpha}{2\beta - \alpha} \frac{\gamma - \rho}{2\alpha +4\beta}
$$

This amount is larger than zero because $2\beta > \alpha \implies 2\beta > \alpha/2$.  Thus, there is no equilibrium in which one gang has weapons and the other gang does not.

\pagebreak

(f) Can this game support a mixed strategy Nash equilibrium? If so, find such an equilibrium. If not, explain why it cannot exist.

This game does not support a mixed strategy Nash equilibrium because the best response to an arbitrary mixed strategy is a pure strategy.  Let gang $j$ play a mixed strategy and gang $i$ maximizes their expected payoff:

\begin{align*}
& \max_{w_i} \{ E_{w_j}[u_i(w_i, w_j)] \} \\
&= \max_{w_i} \{ E_{w_j}[(\gamma - \rho) w_i - \beta (w_i - w_j)^2 -  (\alpha/2)w_i^2 - (\alpha/2) w_i w_j] \} \\
&= \max_{w_i} \{ (\gamma - \rho) w_i - \beta (w_i^2 - 2w_iE_{w_j}[w_j] + E_{w_j}[w_j^2]) -  (\alpha/2)w_i^2 - (\alpha/2) w_i E_{w_j}[w_j] \} 
\end{align*}

FOC [$w_i$]:

$$
0 = (\gamma - \rho) - 2\beta w_i^* + 2E_{w_j}[w_j] -  \alpha w_i^* - (\alpha/2) E_{w_j}[w_j] \\
\implies w_i^* = \frac{(\gamma - \rho)  + 2E_{w_j}[w_j] - (\alpha/2) E_{w_j}[w_j]}{2\beta + \alpha}
$$

Thus, gang $i$'s best response only depends on the expected value of gang $j$'s mixed strategy, so it is a pure-strategy.  Thus, the game does not support a mixed-strategy Nash equilibrium.

(g) Suppose both gangs have the equilibrium quantity of weapons from part (c). A horde of goblins suddenly invades the area. Because weapons can be used to fight goblins, the inherent value $\gamma$ of weapons increases. However, the goblins also steal all the money of gang 2, leaving that gang unable to purchase new weapons. How does gang 1’s weapons quantity respond to this shock? How does the magnitude of this response compare to the magnitude if both gangs were able to respond?

Gang 1's weapons quantity increased due to the shock.  The magnitude of the increase is greater than it would be if both gangs could purchase weapons because gang 2 would also purchase more weapons and thus increasing the market price.

More formally, both gangs have $w_1 = w_2 = \frac{2\gamma - 2\rho}{3\alpha}$ weapons.  Let $\gamma' > \gamma$.  If both gangs have sufficient funds, they would want $w_1' = w_2' = \frac{2\gamma' - 2\rho}{3\alpha}$ weapons.  However, if gang 2 has no money then they are stuck at $w_2'' = \frac{2\gamma - 2\rho}{3\alpha}$.  The price function becomes $P(\bar{w}) = \rho + \alpha (w_1'' + \frac{2\gamma' - 2\rho}{3\alpha})/2$ and gang 1's payoff function becomes:

\begin{align*}
u_1\Bigg(w_1'', \frac{2\gamma - 2\rho}{3\alpha}\Bigg) 
&= \gamma' w_1'' - \beta \Bigg(w_1'' - \frac{2\gamma - 2\rho}{3\alpha}\Bigg)^2 - \Bigg(\rho + \alpha \Bigg(w_1'' + \frac{2\gamma' - 2\rho}{3\alpha}\Bigg)/2\Bigg) w_1'' \\
&= (\gamma' - \rho) w_1'' - \beta \Bigg(w_1'' - \frac{2\gamma - 2\rho}{3\alpha}\Bigg)^2 - (\alpha/2) (w_1'')^2 - w_1''\frac{\gamma' - \rho}{3}
\end{align*}

FOC [$w_1''$]:

\begin{align*}
0 &= (\gamma' - \rho) - 2\beta \Bigg(w_1'' - \frac{2\gamma - 2\rho}{3\alpha}\Bigg) - \alpha w_1'' - \frac{\gamma' - \rho}{3} \\
\implies w_1'' &= \frac{2\alpha(\gamma' - \rho) + 4\beta (\gamma - \rho) }{3\alpha (2\beta + \alpha ) }
\end{align*}

So, $w_1'' > w_1' > w_1$.

\pagebreak

2. Consider the game from question 1, but now with a continuum of gangs. Let the payoffs now depend on the average weapons quantity $\bar{w}$, rather than that of any single other gang: $u_i(w_i, \bar{w}) = \gamma w_i - \beta (w_i - \bar{w})^2 - P(\bar{w}) w_i$.  Find the symmetric pure strategy Nash equilibrium. How and why does the equilibrium quantity of weapons differ from the equilibrium quantity in the two-gang game?

Since there is a continuum of gangs, a single gang does not change $\bar{w}$.

$$
u_i(w_i, \bar{w}) = \gamma w_i - \beta (w_i - \bar{w})^2 - ( \rho + \alpha \bar{w}) w_i
$$

FOC [$w_i$]:

$$
0 = \gamma- 2\beta (w_i^* - \bar{w})-( \rho + \alpha \bar{w})
$$

In a symmetric equilibrium $w_i^* = \bar{w}$:

$$
0 = \gamma - 2\beta (w_i^* - w_i^*) - ( \rho + \alpha w_i^*) \\
w_i^* = \frac{\gamma - \rho}{\alpha} \\
$$

In the 2-player game, gangs buy 2/3 of the weapons they buy in the continuum game.  It's lower because, in the 2-player game, a single gang's move changes the market price.  This is a similar result to the Cournot duopoly in Problem Set 2.

\pagebreak

3. A continuum of agents plays a guessing game, in which each agent $i$ guesses a number $x_i \in [0, 1]$. Agents prefer to guess numbers further from some commonly known constant $\alpha \in (0, 1)$, and dislike guessing further from the average value $\bar{x}$. Each agent's payoff is $u_i(x_i; \bar{x}, \alpha) = (x_i - \alpha)^2 - (x_i - \bar{x})^2$.

(a) Find all symmetric pure strategy Nash equilibria.

Since there's a continuum of agents, no single agent's guess alters the average.  Let us first find an interior solution.  The FOC is $0 = 2(x_i - \alpha) - 2(x_i - \bar{x})$. In a symmetric equilibrium, all agents guess the same number so the agent's $i$ guess is the average guess: $0 = 2(x_i - \alpha) - 2(x_i - x_i)  \implies x_i = \alpha$.

If all agents guess $\alpha$, then agent $i$ have no incentive to change their guess because $u_i(x_i; \alpha, \alpha) = (x_i - \alpha)^2 - (x_i - \alpha)^2 = 0$ for all $x_i \in [0, 1]$. Thus, all agents guessing $\alpha$ is a Nash equilibrium.

Now, let us find any corner solutions.  If all agents guess $0$, then $\bar{x} = 0$.  Let us consider if agent $i$ have any incentive to deviate:

$$
u_i(x_i; 0, \alpha) = (x_i - \alpha)^2 - x_i^2 = x_i^2 - 2x_i\alpha + \alpha^2 - x_i^2 = \alpha^2 - 2x_i\alpha
$$

The above equation is maximized at $x_i = 0$.  Thus, all agents guessing $0$ is a Nash equilibrium.

Similarly, if all agents guess 1 $\implies \bar{x} =1$.  Agent $i$'s utility function is

$$
u_i(x_i; 1, \alpha) = (x_i - \alpha)^2 - (x_i-1)^2 = x_i^2 - 2x_i\alpha + \alpha^2 - x_i^2 +2x_i - 1 = \alpha^2 + 2(1-\alpha)x_i - 1
$$

The above equation is maximized at $x_i = 1$. Thus, all agents guessing $1$ is a Nash equilibrium.

(b) Recall that with a continuum of agents, a Nash equilibrium can be characterized by a quantile function, regardless of whether it is achieved using asymmetric pure strategies or with randomization. Describe all non-degenerate quantile functions that are Nash equilibria in this game, excluding the equilibria found in part (a).

In part (a), we found that, if all other agents guess $\alpha$, agent $i$ cannot become better off by guessing any other number.  This notion extends to any distribution of guesses where the average guess is $\alpha$.  Let $q(x)$ be a quantile function over $[0,1]$ such that $E[q(x)] = \bar{x} = \alpha$.  Agent $i$ has no reason to deviate from her guess because $u_i(x_i; \alpha, \alpha) = (x_i - \alpha)^2 - (x_i - \alpha)^2 = 0$.  Thus, $q(x)$ is a Nash equilibrium.

(c) Now suppose agents can choose any $x \in \R$. Describe all Nash equilibria.

Let $q(x)$ be a quantile function $\R$ such that $E[q(x)] = \bar{x} = \alpha$.  Agent $i$ has no reason to deviate from her guess because $u_i(x_i; \alpha, \alpha) = (x_i - \alpha)^2 - (x_i - \alpha)^2 = 0$.  Thus, $q(x)$ is a Nash equilibrium.

In part (a), we found that degenerate Nash equilibriums where all agents guess 0 and 1.  These equilibria do not extend to the unbounded domain because agents always have an incentive to guess higher (lower) if the average guess is larger (smaller) than $\alpha$.  Say all agents guess $y \in \R \implies \bar{x} = y$. Consider agent $i$ guessing $y' > y$:

\begin{align*}
u_i(y'; y, \alpha) - u_i(y; y, \alpha)
&=  [(y' - \alpha)^2 - (y' - y)^2] - [(y - \alpha)^2 - (y - y)^2] \\
&= [(y')^2 - 2\alpha y'+\alpha^2] - [(y')^2 - 2y'y + y^2] - [y^2 - 2\alpha y + \alpha^2]\\
&= (y')^2 - 2\alpha y'+\alpha^2 - (y')^2 + 2y'y - y^2 - y^2 + 2\alpha y - \alpha^2 \\
&=  2y(y' - y) - 2\alpha (y' - y)  
\end{align*}

If $y' > y > \alpha$, agent $i$ is better off guessing $y'$ than $y$.  Similarly if $y' < y < \alpha$, agent $i$ is better off guessing $y'$ than $y$.  Thus, all agents choosing $y$ is not a Nash equilibrium.

\pagebreak

4. Two players choose numbers in $\R$. Their payoffs are $u_i(q_i, q_j) = q_i + q_i(q_j-1)^{1/3}-\frac{1}{2}q_i^2$. Find all Nash equilibria of this game.

FOC [$q_i$]:

$$
0 = 1 + (q_j-1)^{1/3}-q_i^* \\
\implies q_i^* = 1 + (q_j-1)^{1/3}
$$

The game is symmetric so we can plug in $q_j^* = 1 + (q_i-1)^{1/3}$:

$$
q_i^* = 1 + ((1 + (q_i^*-1)^{1/3})-1)^{1/3} = 1 + ((q_i^*-1)^{1/3})^{1/3} \\
\implies q_i^*-1 = (q_i^*-1)^{1/9}
$$

This equation holds for $q_i^* = 0$, $q_i^* = 1$, and $q_i^* = 2$. Thus, there are pure-strategy Nash equilibriums at $(0, 0)$, $(1, 1)$, and $(2, 2)$.

Since the payoff function is strictly quasi-concave in $q_i$, there are no mixed-strategy Nash equilibriums.

\pagebreak

5. Two players play a game of Rock, Paper, Scissors. In this game, each player simultaneously chooses a strategy from the set $\{$Rock, Paper, Scissors$\}$. Paper beats Rock: if one player chooses Paper and the other chooses Rock, the player choosing Paper receives a payoff of 10, and the other player receives a payoff of 10. Similarly, Scissors beats Paper, and Rock beats Scissors. If both players choose the same pure strategy, each receives a payoff of 0. Players can also choose mixed strategies. However, in order to implement a mixed strategy, a player must rent a randomizing device. The rental costs 1 unit of payoffs. Find all Nash equilibria of this game.

There are no pure-strategy Nash equilibriums.  For example, say player 1 plays Rock and player 2 plays Scissors.  Rock beats Scissors, so player 1 gets a payoff of 10 and player 2 gets a payoff of -10.  Player 2 has an incentive to change to Paper to beat Rock.  Then Player 1 has an incentive to play Scissors to beat Paper. Then Player 2 has an incentive to play Rock to beat Scissors.  Similarly, if both players play Rock (for example), player 1 has an incentive to switch to Paper. Thus, there are no pure-strategy Nash equilibriums.

For mixed-strategy Nash equilibrium, consider player 2 playing Rock with $R$ probability, Scissors with $S$ probability, and Paper with $P$ probability.  The expected payoff of player 1 playing Rock is

$$
R(0) + P(-10)+S(10) -1= 10S-10P-1
$$

The expected payoff of player 1 playing Paper is

$$
R(10) + P(0)+S(-10) -1= 10S-10R-1
$$

The expected payoff of player 1 playing Scissors is

$$
R(-10) + P(10)+S(0) -1= 10P-10R-1
$$

For player 1 to be indifferent between her options:

$$
10P-10R-1 = 10S-10R-1 = 10S-10P-1 \implies P-R = S-R = S-P \implies R=P=S=\frac{1}{3}
$$

Thus, her expected payoff from a mixed-strategy is

$$
1/3(10)+1/3(-10)-1 = -1
$$

Now consider her expected payoff from playing any pure-strategy

$$
1/3(10)+1/3(-10) = 0
$$

Thus, player 1's best response to a mixed strategy is to play pure strategy.  Thus, there are Nash equilibriums.
