---
title: "ECON 714B - Problem Set 4"
author: "Alex von Hafften^[I worked on this problem set with a study group of Michael Nattinger, Andrew Smith, and Ryan Mather. I also discussed problems with Sarah Bass, Emily Case, Danny Edgel, and Katherine Kwok.]"
date: "4/16/2021"
output: pdf_document
header-includes:
- \newcommand{\N}{\mathbb{N}}
- \newcommand{\Z}{\mathbb{Z}}
- \newcommand{\R}{\mathbb{R}}
- \newcommand{\Q}{\mathbb{Q}}
- \newcommand{\Lf}{\mathcal{L}}
- \newcommand{\graph}{\text{graph}}
- \usepackage{bm}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

## Problem 1 (50 points)

Suppose that an infinitely lived government has to finance a fixed stream of expenditures, $\{g_t\}_{t\ge 0}$ and can only use consumption taxes for this purpose. Assume that the representative consumer has the utility function: 

$$
\sum_{t=0}^\infty \beta^t \Bigg[ \frac{c_t^{1-\sigma}}{1-\sigma} + v(\ell_t) \Bigg]
$$ 

where $c_t$ is the consumption in period $t$ and $\ell_t$ is leisure in period $t$. Assume that $\sigma>0$ and $v$ is an increasing function. Also assume that the production function, $F(K,L)$ satisfies all the standard assumptions (i.e., CRS, etc.), that the representative household has an initial endowment of the capital stock, $k_0, \ell_t \le 1$ and that capital is subject to the usual law of motion, $k_{t+1}=(1-\delta)k_t+x_t$. Set up the Ramsey Problem for this economy, and show that the optimal policy is to set the consumption tax at a constant rate from period one onwards (i.e., show that $\tau^{RP}_{t}=\tau^{RP}_{t+1}$ for all $t \ge 1$.

[I'm assuming that the HH is endowed with one unit of time with which they can consume $\ell_t \le 1$ leisure and supply $1 - \ell_t \le 1$ units of labor.]

The feasibility constraint is:

$$
c_t + g_t + k_t = F(k_{t-1}, 1 - \ell_t) + (1 - \delta) k_{t-1}
$$

To find the implementability constraint, we start by defining the HH problem:

$$
\max_{c_t, \ell_t} \sum_{t=0}^\infty \beta^t \Bigg[ \frac{c_t^{1-\sigma}}{1-\sigma} + v(\ell_t) \Bigg]
$$

$$
\text{s.t. } (1 + \tau_t)c_t + k_t + b_t = w_t (1-\ell_t) + (1 - \delta + r_t) k_{t-1} + R^b_t b_{t-1}
$$

Let $p_t$ be the multiplier on the budget constraint, so the legrangian is 

$$
\sum_{t=0}^\infty \beta^t \Bigg[ \frac{c_t^{1-\sigma}}{1-\sigma} + v(\ell_t) \Bigg] +
p_t\Big[ w_t (1-\ell_t) + (1 - \delta + r_t) k_{t-1} + R^b_t b_{t-1} - (1 + \tau_t)c_t - k_t - b_t \Big]
$$

\pagebreak

The FOCs are:

\begin{align}
\beta^t c_t^{-\sigma} &= p_t (1+\tau_t) & [c_t] \\
\beta^t v'(\ell_t) &= p_t w_t & [\ell_t] \\
[p_t - p_{t+1} R^b_{t+1}] b_t &= 0 & [b_t] \\
[p_t - p_{t+1} (1 + r_{t+1} - \delta)] k_t &= 0 &[k_t]
\end{align}

Multiply the HH budget constraint and sum across $t$:

$$
\sum_{t=0}^\infty p_t[(1 + \tau_t)c_t + k_t + b_t] = \sum_{t=0}^\infty p_t[w_t (1-\ell_t) + (1 - \delta + r_t) k_{t-1} + R^b_t b_{t-1}]
$$

Substituting in (3), we can cancel out bond holdings in every period except for the initial period:

$$
\sum_{t=0}^\infty p_t[(1 + \tau_t)c_t + k_t] = p_0R^b_0 b_{-1} + \sum_{t=0}^\infty p_t[w_t (1-\ell_t) + (1 - \delta + r_t) k_{t-1} ]
$$

Substituting in (4), we can cancel out capital holdings in every period except for the initial period:

$$
\sum_{t=0}^\infty p_t(1 + \tau_t)c_t = p_0R^b_0 b_{-1} + p_0(1 - \delta + r_0) k_{-1} + \sum_{t=0}^\infty p_t w_t (1-\ell_t)
$$

Substituting in (5) and (6), we get the implementability constraint:

$$
\sum_{t=0}^\infty \beta^t c_t^{-\sigma} c_t = p_0 [R^b_0 b_{-1} + (1 - \delta + r_0) k_{-1} ] + \sum_{t=0}^\infty \beta^t v'(\ell_t) (1-\ell_t)
$$

$$
\implies \sum_{t=0}^\infty \beta^t [c_t^{1-\sigma} - v'(\ell_t) (1-\ell_t)] = \frac{c_0^{-\sigma}}{1 + \tau_0} [ R^b_0 b_{-1} + (1 - \delta + r_0) k_{-1} ]
$$

Thus, the feasibility and implementability constraints are necessary and sufficient conditions for an allocation to be a CE.  Thus, the Ramsey problem is

$$
\max_{c_t, \ell_t} \sum_{t=0}^\infty \beta^t \Bigg[ \frac{c_t^{1-\sigma}}{1-\sigma} + v(\ell_t) \Bigg]
$$

$$
\text{s.t. }\sum_{t=0}^\infty \beta^t [c_t^{1-\sigma} - v'(\ell_t) (1-\ell_t)] = \frac{c_0^{-\sigma}}{1 + \tau_0} [ R^b_0 b_{-1} + (1 - \delta + r_0) k_{-1} ]
$$

$$
\text{and }  c_t + g_t + k_t = F(k_{t-1}, 1 - \ell_t) + (1 - \delta) k_{t-1}, \forall t
$$

\pagebreak

We can rewrite the Ramsay problem as:

$$
\max_{c_t, \ell_t} \sum_{t=0}^\infty \beta^t \Bigg[ \frac{c_t^{1-\sigma}}{1-\sigma} + v(\ell_t) \Bigg] + \lambda \Bigg[\sum_{t=0}^\infty \beta^t [c_t^{1-\sigma} - v'(\ell_t) (1-\ell_t)] - \frac{c_0^{-\sigma}}{1 + \tau_0} [ R^b_0 b_{-1} + (1 - \delta + r_0) k_{-1} ]\Bigg]
$$

$$
\implies
\max_{c_t, \ell_t} \sum_{t=0}^\infty \beta^t \Bigg[ \frac{c_t^{1-\sigma}}{1-\sigma} + v(\ell_t) + \lambda  [c_t^{1-\sigma} - v'(\ell_t) (1-\ell_t)]\Bigg] 
- \lambda \frac{c_0^{-\sigma}}{1 + \tau_0} [ R^b_0 b_{-1} + (1 - \delta + r_0) k_{-1} ]
$$

$$
\implies
\max_{c_t, \ell_t} \sum_{t=0}^\infty \beta^t w(c_t, \ell_t, \lambda)
- \lambda \frac{c_0^{-\sigma}}{1 + \tau_0} [ R^b_0 b_{-1} + (1 - \delta + r_0) k_{-1} ]
$$

$$
\text{s.t. } c_t + g_t + k_t = F(k_{t-1}, 1 - \ell_t) + (1 - \delta) k_{t-1}, \forall t
$$

where $w(c_t, \ell_t, \lambda) := \frac{c_t^{1-\sigma}}{1-\sigma} + v(\ell_t) + \lambda  [c_t^{1-\sigma} - v'(\ell_t) (1-\ell_t)]$.  Assume that $\tau_0$ is bounded.  Thus, the Ramsey problem is:

$$
\max_{c_t, \ell_t} \sum_{t=0}^\infty \beta^t w(c_t, \ell_t, \lambda)
$$

$$
\text{s.t. } c_t + g_t + k_t = F(k_{t-1}, 1 - \ell_t) + (1 - \delta) k_{t-1}, \forall t
$$

Let $\gamma_t$ be the multiplier on the feasibility constraint:

$$
\sum_{t=0}^\infty \beta^t w(c_t, \ell_t, \lambda) 
+ \gamma_t [ F(k_{t-1}, 1 - \ell_t) + (1 - \delta) k_{t-1} - c_t - g_t - k_t]
$$

The FOCs are 

\begin{align}
\beta^t w_1(c_t, \ell_t, \lambda) &= \gamma_t & [c_t] \\
\beta^t w_2(c_t, \ell_t, \lambda) &= \gamma_t F_2(k_{t-1}, 1 - \ell_t) & [\ell_t] \\
\gamma_{t+t} [F_1(k_t, 1 - \ell_{t+1}) + (1-\delta)] &= \gamma_t & [k_t]
\end{align}

(5) and (6) imply an intra-temporal FOC:

$$
\frac{w_2(c_t, \ell_t, \lambda)}{w_1(c_t, \ell_t, \lambda)} = F_2(k_{t-1}, 1 - \ell_t)
$$

(5) and (7) imply an inter-temporal FOC:

\begin{align}
\frac{w_1(c_t, \ell_t, \lambda)}{w_1(c_{t+1}, \ell_{t+1}, \lambda)} = \beta [1-\delta + F_1(k_t, 1 - \ell_{t+1})]
\end{align}

\pagebreak

Notice that:

$$
w_1(c_t, \ell_t, \lambda) = c_t^{-\sigma} + \lambda  (1-\sigma)c_t^{-\sigma} = (1 + \lambda - \lambda\sigma)c_t^{-\sigma}
$$

$$
\implies \frac{w_1(c_t, \ell_t, \lambda)}{w_1(c_{t+1}, \ell_{t+1}, \lambda)}
= \frac{(1 + \lambda - \lambda\sigma)c_{t+1}^{-\sigma}}{(1 + \lambda - \lambda\sigma)c_t^{-\sigma}} 
= \frac{c_{t+1}^{-\sigma}}{c_t^{-\sigma}}
$$

Thus, (8) becomes:

\begin{align}
\implies
\frac{c_{t+1}^{-\sigma}}{c_t^{-\sigma}} 
= \beta [1-\delta + F_1(k_t, 1 - \ell_{t+1})]
\end{align}

Let us compare (9) with the HH's intertemporal FOC. In a competitive equilibrium, firms optimize so $r_t = F_1(k_{t-1}, 1- \ell_t)$.  Combining this with (1) and (4), we get

$$
\frac{c_t^{-\sigma}}{c_{t+1}^{-\sigma}} = \beta \frac{1+\tau_t }{1+\tau_{t+1}} [1 + F_1(k_{t-1}, 1- \ell_t) - \delta]
$$

For the Ramsey intertemporal FOC and the HH intertemporal FOC to both hold:

$$
\frac{1+\tau_t }{1+\tau_{t+1}} = 1 \implies \tau_t = \tau_{t+1}
$$

Thus, consumption taxes should be constant for all periods $t \ge 1$.

\pagebreak

## Problem 2 (50 points)

Consider a cash-credit goods economy with preferences given by

$$
\log c_{1,t}+\alpha \log c_{2,t} + \gamma \log(1-n_t)
$$

where $n_t$ is the time spent in market activities. The resource constraint is

$$
c_{1,t}+c_{2,t}=n_t
$$

The cash-in-advance constraint is 

$$
p_t c_{1,t} \le M_t
$$

The budget constraint for the HH at the beginning of the period is

$$
M_t+B_t \le (M_{t-1}-p_{t-1}c_{1,t-1})-p_{t-1}c_{2,t-1}+w_{t-1}n_{t-1}+R_{t-1}B_{t-1}-T_t
$$

where $T_t$ denotes lump-sum taxes and all the terms are as we discussed in class. The government conducts monetary policy to keep the interest rate fixed at some level $R$ in all periods.

1. Define a competitive equilibrium.

Notice that the production function is $F(n_t) = n_t$. If firms are competitive, then the real wage is the marginal product of labor, so it equals one and the nominal wage is $w_t = p_t$.

A competitive equilibrium is an allocation $x = \{(c_{1,t}, c_{2,t}, n_t)\}_{t=0}^\infty$, a price system $q = \{(p_{t}, R_t)\}_{t=0}^\infty$, and a policy $\pi = \{(M_t, B_t, T_t)\}_{t=0}^\infty$ such that 

(1) Given $\pi$ and $q$, $x$ solves the HH problem:

$$
\max_{(c_{1,t}, c_{2,t}, n_t)} \sum_{t=0}^\infty  \beta^t [\log c_{1,t}+\alpha \log c_{2,t} + \gamma \log(1 - n_t)]
$$

$$
\text{s.t. }
M_t + B_t = (M_{t-1} - p_{t-1} c_{1,t-1}) - p_{t-1} c_{2,t-1} + p_{t-1}n_{t-1} + R_{t-1} B_{t-1} - T_t
$$

$$
\text{and }
p_t c_{1,t} = M_t
$$

(2) $x$, $q$, and $\pi$ satisfy the government BC:

$$
M_t - M_{t-1} + B_t + T_t = R_{t-1}B_{t-1}
$$

(3) Markets clear:

$$
c_{1,t}+c_{2,t}=n_t
$$

From the problem setup, we know that $R_t = R$ for all $t$.

\pagebreak

2. What happens to $n_t$ as $R$ increases. Prove your result.

If $\gamma > 0$, then $n_t$ decreases when $R$ increases.  To prove it, let's solve for a competitive equilibrium.  Let $\xi_t$ be the multiplier on the cash-in-advance constraint and $\lambda_t$ be the multiplier on the HH budget constraint:

\begin{align*}
\sum_{t=0}^\infty & \beta^t [\log c_{1,t}+\alpha \log c_{2,t} + \gamma \log(1 - n_t)] + \xi_t [M_t - p_t c_{1,t}] \\
&+ \lambda_t [(M_{t-1}-p_{t-1}c_{1,t-1})-p_{t-1}c_{2,t-1}+p_{t-1}n_{t-1}+RB_{t-1}-T_t - M_t - B_t] 
\end{align*}

Thus, the FOCs are:

\begin{align}
\frac{\beta^t}{c_{1,t}} &= \lambda_{t+1}p_t + \xi_t p_t & [c_{1,t}]\\
\frac{\beta^t\alpha}{c_{2,t}} &= \lambda_{t+1}p_t       & [c_{2,t}]\\
\frac{\beta^t\gamma}{1- n_t} &= \lambda_{t+1}p_{t}      & [n_{t}]\\
\lambda_t &= \lambda_{t+1} R                            & [B_{t}]\\
\lambda_t &= \lambda_{t+1} + \xi_{t}                    & [M_{t}]
\end{align}

(13) and (14) imply

$$
\lambda_{t+1}R = \lambda_{t+1} + \xi_t
$$

Substituting in (10), we get

$$
 R\lambda_{t+1}p_t = \frac{\beta^t}{c_{1,t}}
$$

Substituting in (12), we get

$$
R \frac{\beta^t\alpha}{c_{2,t}} = \frac{\beta^t}{c_{1,t}} 
\implies 
c_{1,t} = \frac{c_{2,t}}{R \alpha}
$$

Combining (11) and (12), we get

$$
\frac{\alpha}{c_{2,t}} = \frac{\gamma}{1- n_t} \implies c_{2, t} = \frac{\alpha(1-n_t)}{\gamma}
$$

Market clearing implies:

$$
n_t = \frac{1}{R \alpha}\frac{\alpha(1-n_t)}{\gamma} + \frac{\alpha(1-n_t)}{\gamma} \\
\implies
n_t=  \frac{1  + \alpha R}{1 + (\alpha + \gamma)R}
$$

The derivative with respect to $R$ is:

$$
\frac{\partial n_t}{\partial R} = \frac{- \gamma}{[(\alpha + \gamma)R + 1]^2}
$$

If $\gamma > 0$, then $n_t$ decreases when $R$ increases.
