---
title: "ECON 714A - Problem Set 2"
author: "Alex von Hafften^[I worked on this problem set with a study group of Michael Nattinger, Andrew Smith, and Ryan Mather. I also discussed problems with Sarah Bass, Emily Case, Danny Edgel, and Katherine Kwok.]"
date: "2/8/2020"
output: pdf_document
header-includes:
- \newcommand{\N}{\mathbb{N}}
- \newcommand{\Z}{\mathbb{Z}}
- \newcommand{\R}{\mathbb{R}}
- \newcommand{\Q}{\mathbb{Q}}
- \newcommand{\Lf}{\mathcal{L}}
- \newcommand{\graph}{\text{graph}}
- \usepackage{bm}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Consider a growth model with preferences $\sum_{t=0}^\infty \beta^t \log C_t$, production function $Y_t=AK_t^\alpha$, the capital law of motion $K_{t+1}=K^{1-\delta}_t I^\delta_t$, and the resource constraint $Y_t=C_t+I_t$.

1. Write down the social planner’s problem and derive the Euler equation. Provide the intuition to this optimality condition using the perturbation argument.

The social planner's problem is

\begin{align*}
\max_{\{C_t, K_t\}_{t=0}^\infty} & \sum_{t=0}^\infty \beta^t \log C_t \\
\text{s.t. } AK_t^\alpha &= C_t+I_t \\
K_{t+1} &= K^{1-\delta}_t I^\delta_t \\
\implies
\max_{\{C_t, K_t\}_{t=0}^\infty} & \sum_{t=0}^\infty \beta^t \log C_t \\
\text{s.t. } 0 &= K^{1-\delta}_t (AK_t^\alpha - C_t)^\delta - K_{t+1}
\end{align*}

The legrangian is

$$
\sum_{t=0}^\infty \beta^t \log C_t + \lambda_t [K^{1-\delta}_t (AK_t^\alpha - C_t)^\delta - K_{t+1}]
$$

FOC ($C_t$):

\begin{align*}
0 &= \frac{\beta^t}{C_t} - \lambda_t \delta K^{1-\delta}_t (AK_t^\alpha - C_t)^{\delta-1} \\
\implies 
\lambda_t &= \frac{\beta^t}{C_t\delta K^{1-\delta}_t I_t^{\delta-1}}
\end{align*}

\pagebreak

FOC ($K_{t+1}$):

\begin{align*}
0 &= -\lambda_t + \lambda_{t+1}[(1-\delta)  K^{-\delta}_{t+1} (AK_{t+1}^\alpha - C_{t+1})^\delta + \delta  K^{1-\delta}_{t+1} (AK_{t+1}^\alpha - C_{t+1})^{\delta-1}A\alpha K_{t+1}^{\alpha-1}]\\
\implies
\frac{\lambda_t}{\lambda_{t+1}} &= (1-\delta) (\frac{I_{t+1}}{K_{t+1}})^\delta + \delta  (\frac{I_{t+1}}{K_{t+1}})^{\delta-1}A\alpha K_{t+1}^{\alpha-1}
\end{align*}

FOCs imply the consumption Euler equation:

\begin{align*}
\frac{(\frac{\beta^t}{C_t\delta K^{1-\delta}_t I_t^{\delta-1}})}
{(\frac{\beta^{t+1}}{C_{t+1} \delta K^{1-\delta}_{t+1} I_{t+1}^{\delta-1}})}
&= (1-\delta) (\frac{I_{t+1}}{K_{t+1}})^\delta + \delta  (\frac{I_{t+1}}{K_{t+1}})^{\delta-1}A\alpha K_{t+1}^{\alpha-1} \\
\implies
\frac{C_{t+1}  K^{1-\delta}_{t+1} I_{t+1}^{\delta-1}}
{\beta C_t K^{1-\delta}_t I_t^{\delta-1}}
&= (1-\delta) (\frac{I_{t+1}}{K_{t+1}})^\delta + \delta  (\frac{I_{t+1}}{K_{t+1}})^{\delta-1}A\alpha K_{t+1}^{\alpha-1} \\
\implies
C_t^{-1}  
&= C_{t+1}^{-1}  \beta 
(\frac{ K_t }{K_{t+1} })^{1-\delta}
(\frac{ I_t}{I_{t+1}})^{\delta-1}
[(1-\delta) (\frac{I_{t+1}}{K_{t+1}})^\delta + \delta  (\frac{I_{t+1}}{K_{t+1}})^{\delta-1}A\alpha K_{t+1}^{\alpha-1}] \\
&= C_{t+1}^{-1}  \beta 
\Bigg(\frac{K_t}{I_t}\Bigg)^{1-\delta}
\Bigg[(1-\delta) \frac{I_{t+1}}{K_{t+1}} + \delta  A\alpha K_{t+1}^{\alpha-1}\Bigg] \\
&= C_{t+1}^{-1}  \beta 
\Bigg(\frac{K_{t+1}}{I_t}\Bigg)
\Bigg[(1-\delta) \frac{I_{t+1}}{K_{t+1}} + \delta  A\alpha K_{t+1}^{\alpha-1}\Bigg] \\
&= C_{t+1}^{-1}  \beta 
\Bigg[(1-\delta) \frac{I_{t+1}}{I_{t}} + \delta \frac{\alpha Y_{t+1}}{I_t}\Bigg]
\end{align*}

Or in just in terms of capital and consumption:

\begin{align*}
C_t^{-1}  
&= C_{t+1}^{-1}  \beta 
\Bigg[(1-\delta) \frac{I_{t+1}}{I_{t}} + \delta \frac{\alpha Y_{t+1}}{I_t}\Bigg] \\
&= C_{t+1}^{-1}  \beta 
\Bigg[(1-\delta) \frac{Y_{t+1} - C_{t+1}}{Y_{t} - C_{t}} + \delta \frac{\alpha Y_{t+1}}{Y_{t} - C_{t}}\Bigg] \\
&= C_{t+1}^{-1}  \beta 
\Bigg[(1-\delta) \frac{AK_{t+1}^\alpha - C_{t+1}}{AK_{t}^\alpha - C_{t}} 
+ \delta \frac{\alpha AK_{t+1}^\alpha}{AK_{t}^\alpha - C_{t}}\Bigg]
\end{align*}

Perturbation argument:

To argue that the EE represents the optimal path, let us consider a deviation from the optimal path for capital and the approximate effect on utility.  In particular, consumption at $t$ increase reducing investment and thus reducing capital in $t+1$ ($\uparrow C_t \to \downarrow I_t \to \downarrow K_{t+1}$).  The reduced capital reduces output in $t+1$ ($\downarrow K_{t+1} \to \downarrow Y_{t+1}$).  Thus to return to the optimal path for capital in $t+2$, investment needs to make up for the lower depreciated capital from $t+1$ reducing consumption ($\uparrow I_{t+1} \to \downarrow C_{t+1}$). In addition, consumption in $t+1$ is reduced both because output in $t+1$ is lower ($\downarrow Y_{t+1} \to \downarrow C_{t+1}$).

\pagebreak

Assume we're on the optimal path for capital $\{K_t\}_{t=0}^\infty$ and a deviation at some $t$ such that $\tilde{K}_{t+1} < K_{t+1}$. To achieve such a deviation, $\tilde{C}_t = C_t + \Delta$ for some $\Delta > 0$. The feasibility constraint implies that $\tilde{I}_t = I_t - \Delta$.  Thus, capital in period $t+1$ can be approximated as:

\begin{align*}
\tilde{K}_{t+1} 
&= \tilde{K}_t^{1-\delta} \tilde{I}_t^\delta \\
&= K_t^{1-\delta} (I_t - \Delta)^\delta \\
& \approx K_t^{1-\delta} I_t^{\delta} - \delta K_t^{1-\delta}I_t^{\delta-1} \Delta \\
&= K_{t+1} -  \Delta\frac{\delta K_{t+1} }{I_t}
\end{align*}

Investment in $t+1$ needs to return capital to the optimal path in $t+2$:

\begin{align*}
\tilde{K}_{t+2} &= K_{t+2} \\
\implies \tilde{K}_{t+1}^{1-\delta} \tilde{I}_{t+1}^\delta &= K_{t+1}^{1-\delta} I_{t+1}^\delta \\
\implies \tilde{I}_{t+1}
&= I_{t+1} K_{t+1}^{\frac{1-\delta}{\delta}} (K_{t+1} -  K_{t+1}\frac{\delta \Delta}{I_t})^{\frac{\delta-1}{\delta}} \\
&\approx I_{t+1} K_{t+1}^{\frac{1-\delta}{\delta}} K_{t+1} ^{\frac{\delta-1}{\delta}} 
+ (-  K_{t+1}\frac{\delta \Delta}{I_t}) \frac{\delta-1}{\delta} I_{t+1} K_{t+1}^{\frac{1-\delta}{\delta}} K_{t+1}^{\frac{\delta-1}{\delta}-1}  \\
&= I_{t+1} + \Delta\frac{(1-\delta)I_{t+1}}{I_t}
\end{align*}

In addition, with lower capital, production in $t+1$ is less:

\begin{align*}
\tilde{Y}_{t+1} 
&= A\tilde{K}_{t+1}^\alpha \\
&= A\Bigg(K_{t+1} - \frac{\delta K_{t+1} \Delta}{I_t}\Bigg)^\alpha \\
&\approx  AK_{t+1}^\alpha - A \alpha K_{t+1}^{\alpha - 1}\frac{\delta K_{t+1} \Delta}{I_t}\\ 
&= Y_{t+1} - \Delta \frac{ \alpha \delta Y_{t+1}}{I_t}
\end{align*}

Thus, consumption in $t+1$ is less:

\begin{align*}
\tilde{Y}_{t+1} &= \tilde{C}_{t+1} + \tilde{I}_{t+1} \\ 
\implies Y_{t+1} - \Delta\frac{ \alpha \delta Y_{t+1}}{I_t} &= \tilde{C}_{t+1} + (I_{t+1} + \Delta(1-\delta)\frac{I_{t+1}}{I_t}) \\ 
\implies \tilde{C}_{t+1} 
&= Y_{t+1} - \Delta\frac{ \alpha \delta Y_{t+1}}{I_t} - I_{t+1} - \Delta \frac{(1-\delta)I_{t+1}}{I_t} \\ 
&= C_{t+1} - \Delta\Bigg[(1-\delta)\frac{I_{t+1}}{I_t} + \delta \frac{ \alpha  Y_{t+1} }{I_t}\Bigg]
\end{align*}

\pagebreak

At on the optimal path, the discounted marginal utility of deviating from the optimal path is zero:

\begin{align*}
0 &= u'(\tilde{C}_t) + \beta u'(\tilde{C}_{t+1}) \\
\implies 0 &= u'(C_t)\Delta - \beta u'(C_{t+1}) \Delta  \Bigg[(1-\delta)\frac{I_{t+1}}{I_t} + \delta \frac{ \alpha  Y_{t+1} }{I_t}\Bigg] \\
\implies 0 &= C_t^{-1}\Delta - \beta C_{t+1}^{-1} \Delta  \Bigg[(1-\delta)\frac{I_{t+1}}{I_t} + \delta \frac{ \alpha  Y_{t+1} }{I_t}\Bigg]\\
\implies C_{t}^{-1} &= C_{t+1}^{-1}  \beta \Bigg[(1-\delta)\frac{I_{t+1}}{I_t} + \delta \frac{ \alpha  Y_{t+1} }{I_t}\Bigg]
\end{align*}

This equation matches the Euler equation above.

2. Derive the system of equations that pins down the steady state of the model.

In a steady state, $C_t = C_{t+1} = \bar{C}, K_t = K_{t+1} = \bar{K}$, and $I_t = I_{t+1} = \bar{I}$.  

From the law of motion of capital:

$$
\bar{K}=\bar{K}^{1-\delta} \bar{I}^\delta \implies \bar{K} = \bar{I}
$$

From the consumption Euler equation and $\bar{K} = \bar{I}$:

$$
\bar{C}^{-1} 
= \bar{C}^{-1} \beta 
(\frac{\bar{K}}{\bar{K}})^{1-\delta}
[(1-\delta) \frac{\bar{K}}{\bar{K}} + \delta  A\alpha \bar{K}^{\alpha-1}] 
\implies
\bar{K} = \Bigg(\frac{\frac{1}{\beta} - 1 + \delta}
{\delta  A\alpha}\Bigg)^\frac{1}{\alpha - 1}
$$

From the resource constraint and $\bar{K} = \bar{I}$:

$$
\bar{Y} = A\bar{K}^\alpha = \bar{C}+\bar{K} \implies  \bar{C} = A\bar{K}^\alpha -\bar{K} 
$$

3. Log-linearize the equilibrium conditions around the steady state.

We log-linearize around the steady state.

Output log-deviations around the steady state can be approximated as:

\begin{align*}
Y_t &= AK_t^\alpha \\
\implies \bar{Y}(1+y_t) &= A\bar{K}^\alpha(1+\alpha k_t)\\
\implies y_t &= \alpha k_t
\end{align*}

\pagebreak

Investment log-deviations around the steady state can be approximated as:

\begin{align*}
I_t &= Y_t - C_t \\
\implies 
\bar{I}(1 + i_t) &= \bar{Y}(1 + y_t) - \bar{C}(1 + c_t) \\
\implies 
i_t &= \frac{\bar{Y}}{\bar{I}}y_t - \frac{\bar{C}}{\bar{I}}c_t \\
&= \frac{A\bar{K}^\alpha}{\bar{K}}\alpha k_t - \frac{\bar{C}}{\bar{K}}c_t\\
&= A\bar{K}^{\alpha-1} \alpha k_t - \frac{\bar{C}}{\bar{K}}c_t\\
&= \phi \alpha k_t - \frac{\bar{C}}{\bar{K}}c_t \\
&= \phi \alpha k_t - (\phi - 1) c_t
\end{align*}

where $\phi \equiv A\bar{K}^{\alpha-1}$.  From the capital steady state, we know that $\delta  \alpha \phi + 1 - \delta = \frac{1}{\beta}$ and $\bar{C}/\bar{K} = \phi - 1$.  

Capital log-deviations around the steady state can be approximated from the law of motion of capital as:

\begin{align*}
K_{t+1} &= K^{1-\delta}_t I^\delta_t \\
\implies k_{t+1} &= (1-\delta)k_t + \delta i_t \\
&= (1-\delta)k_t + \delta (\phi \alpha k_t - \frac{\bar{C}}{\bar{K}}c_t)\\
&= (1-\delta + \delta \phi \alpha )k_t - \delta \frac{\bar{C}}{\bar{K}}c_t \\
&= \frac{1}{\beta}k_t - \delta (\phi - 1) c_t
\end{align*}

\pagebreak

Turning to the Euler equation, 

\begin{align*}
C_t^{-1}  
&= C_{t+1}^{-1}  \beta \Bigg[(1-\delta) \frac{I_{t+1}}{I_{t}} + \delta \frac{\alpha Y_{t+1}}{I_t}\Bigg] \\
\implies
\bar{C}(1+c_{t+1})  
&= \bar{C}(1+c_{t})  \beta \Bigg[(1-\delta) \frac{\bar{I}(1+i_{t+1})}{\bar{I}(1+i_{t})} + \delta \frac{\alpha \bar{Y}(1+y_{t+1})}{\bar{I}(1+i_{t})}\Bigg] \\
\implies
(1+c_{t+1})  
&= (1+c_{t})  \beta \Bigg[(1-\delta) \frac{(1+i_{t+1})}{(1+i_{t})} + \delta \frac{\alpha A\bar{K}^\alpha(1+y_{t+1})}{\bar{K}(1+i_{t})}\Bigg] \\
\implies
(1+c_{t+1})  
&= (1+c_{t})  \beta \Bigg[(1-\delta) \frac{(1+i_{t+1})}{(1+i_{t})} + \delta \frac{\alpha \phi(1+y_{t+1})}{(1+i_{t})}\Bigg] \\
\implies
(1+c_{t+1})(1+i_{t})  
&= (1+c_{t})  \beta \Bigg[(1-\delta) (1+i_{t+1}) + \delta \alpha \phi(1+y_{t+1})\Bigg] \\
\implies
1+c_{t+1}+i_{t}+c_{t+1}i_{t}  
&= (1+c_{t})  \beta \Bigg[1-\delta + (1-\delta)i_{t+1} + \delta \alpha \phi + \delta \alpha \phi y_{t+1}\Bigg] \\
\implies
1+c_{t+1}+i_{t}+c_{t+1}i_{t}  
&= (1+c_{t})  \beta \Bigg[1/\beta + (1-\delta)i_{t+1} + \delta \alpha \phi y_{t+1}\Bigg] \\
\implies
c_{t+1}+i_{t}+c_{t+1}i_{t}  
&= c_{t} + (1+c_{t})  \beta \Bigg[(1-\delta)i_{t+1} + \delta \alpha \phi y_{t+1}\Bigg] \\
\implies
c_{t+1}+i_{t}+c_{t+1}i_{t} 
&= c_{t} + (1+c_{t})  \beta \Bigg[(1-\delta)(\phi \alpha k_{t+1} - (\phi-1)c_{t+1}) + \delta \alpha^2 \phi k_{t+1}\Bigg] \\
\implies
c_{t+1}+\phi \alpha k_t -(\phi-1)c_t+ c_{t+1}\phi \alpha k_t - c_{t+1}(\phi-1)c_t  
&= c_{t} + (1+c_{t})  \beta (\frac{1}{\beta}k_t - \delta (\phi-1)c_t)\alpha\phi(1-\delta  + \delta \alpha  ) \\
&-(1+c_{t})  \beta  (1-\delta)(\phi-1)c_{t+1} \\
\end{align*}

\pagebreak

4. Write down a dynamic system with one state variable and one control variable. Use the Blanchard-Kahn method to solve this system for a saddle path.

\begin{align*}
x_t 
&= \begin{pmatrix} k_t \\ c_t \end{pmatrix} \\
x_{t+1} 
&= Ax_{t} \\
&= Q \Lambda Q^{-1}x_t \\
y_t &= Q^{-1}x_t\\
\implies y_{t+1}
&= \Lambda y_t \\
\Lambda &= \begin{pmatrix} \lambda_1 & 0 \\
0 & \lambda_2 \end{pmatrix} \\
\lambda_1 &= \frac{1}{\beta (1 - \delta + \delta \alpha)} \\
\lambda_2 &= 1 - \delta + \delta \alpha
\end{align*}

(Eigenvalues are from Duong's email on February 7th).

Assume $\alpha < 1$ so production has decreasing returns to scale. Since $\alpha < 1$ and $\delta < 1 \implies \lambda_2 < 1$; this eigenvalue cooresponds to the saddle path. 

Furthermore, $\lambda_2 < 1$ and $\beta < 1 \implies \lambda_1 > 1$. If $y_{1,0} \neq 0 \implies y_{1,t} = \lambda_1^t y_{1,0} \to \infty$ as $t \to \infty$. Thus, by the transversality condition, we know that on the saddle path, $y_{1,t} = 0$. Thus,

\begin{align*}
y_t &= Q^{-1} x_t \\
\implies 
\begin{pmatrix} 0 \\ y_{2,t} \end{pmatrix} &= \begin{pmatrix} Q^{-1}_{11} & Q^{-1}_{12} \\ Q^{-1}_{21} & Q^{-1}_{22}  \end{pmatrix} \begin{pmatrix} k_t \\ c_t \end{pmatrix} \\
\implies 
0 &= Q^{-1}_{11} k_t + Q^{-1}_{12} c_t \\
\implies
c_t 
&= \frac{- Q^{-1}_{11}}{Q^{-1}_{12}} k_t \\
&= z k_t \\
\end{align*}

where $z = \frac{- Q^{-1}_{11}}{Q^{-1}_{12}}$.

5. Show that the obtained solution is not just locally accurate, but is in fact the exact solution to the planner’s problem.

...

6. Generalize the (global) solution to the case of stochastic productivity shocks $A_t$.

...

7. The analytical tractability of the model is due to special functional form assumptions, which however, have strong economic implications. What is special about consumption behavior in this model? Provide economic intuition.

...

8. Bonus task: can you introduce labor into preferences and production function without compromising the analytical tractability of the model?

...


