---
title: "ECON 714A - Problem Set 4"
author: "Alex von Hafften^[I worked on this problem set with a study group of Michael Nattinger, Andrew Smith, and Ryan Mather. I also discussed problems with Sarah Bass, Emily Case, Danny Edgel, and Katherine Kwok.]"
date: "2/22/2021"
output: pdf_document
header-includes:
- \newcommand{\N}{\mathbb{N}}
- \newcommand{\Z}{\mathbb{Z}}
- \newcommand{\R}{\mathbb{R}}
- \newcommand{\Q}{\mathbb{Q}}
- \newcommand{\Lf}{\mathcal{L}}
- \newcommand{\graph}{\text{graph}}
- \usepackage{bm}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

This problem asks you to solve a model of oligopolistic competition from Atkeson and Burstein (AER 2008), which extends the Dixit-Stiglitz setup and is widely used to analyze heterogeneous markups and incomplete pass-through.

Consider a static model with a continuum of sectors $k\in[0,1]$ and $i= 1,..N_k$ firms in sector $k$, each producing a unique variety of the good. Households supply inelastically one unit of labor and have nested-CES preferences:

$$
C = \Bigg( \int C_k^{\frac{\rho - 1}{\rho}} dk \Bigg)^{\frac{\rho}{\rho - 1}}, 
C_k = \Bigg( \sum_{i=1}^{N_k} C_{ik}^{\frac{\theta - 1}{\theta}} \Bigg)^{\frac{\theta}{\theta - 1}}, 
\theta > \rho \ge 1.
$$

Production function of firm $i$ in sector $k$ is given by $Y_{ik} = A_{ik} L_{ik}$.

1. Solve household cost minimization problem for the optimal demand $C_{ik}$, the sectoral price index $P_k$, and the aggregate price index $P$ as functions of producers’ prices.

Notice that labor is inelastically supplied.  The household cost minization problem is:

$$
\min_{\{C_{ik}\}}
\int \sum_{i=1}^{N_k} P_{ik} C_{ik} dk
$$
$$
\text{s.t. }
C = \Bigg( \int C_k^{\frac{\rho - 1}{\rho}} dk \Bigg)^{\frac{\rho}{\rho - 1}} \\
$$
$$
\text{and }
C_k = \Bigg( \sum_{i=1}^{N_k} C_{ik}^{\frac{\theta - 1}{\theta}} \Bigg)^{\frac{\theta}{\theta - 1}}
$$

Define the legrange multiplers with $P$ and $P_k$:

$$
\Lf 
= \int \sum_{i=1}^{N_k} P_{ik} C_{ik} dk +
P \Bigg[C - \Bigg( \int C_k^{\frac{\rho - 1}{\rho}} dk \Bigg)^{\frac{\rho}{\rho - 1}}\Bigg] +
\int P_k  \Bigg[C_k - \Bigg( \sum_{i=1}^{N_k} C_{ik}^{\frac{\theta - 1}{\theta}} \Bigg)^{\frac{\theta}{\theta - 1}} \Bigg] dk
$$

\pagebreak

FOC [$C_{k}$]:

\begin{align*}
P_{k} &= P \frac{\rho}{\rho - 1}\Bigg( \int C_{k}^{\frac{\rho - 1}{\rho}} dk \Bigg)^{\frac{1}{\rho - 1}} \frac{\rho - 1}{\rho}C_{k}^{\frac{- 1}{\rho}} \\
\implies
P_{k} &= P\Bigg( \int C_{k}^{\frac{\rho - 1}{\rho}} dk \Bigg)^{\frac{1}{\rho - 1}}  C_{k}^{\frac{- 1}{\rho}} \\
\implies
P_{k} &= P C^{\frac{1}{\rho}}  C_{k}^{\frac{- 1}{\rho}} \\
\implies
C_{k} &= \Bigg( \frac{P_{k}}{P} \Bigg)^{-\rho} C
\end{align*}

Substituting into the constraint, we get the aggregate price index in terms of the sectoral price indexes:

\begin{align*}
C &= \Bigg( \int \Bigg(\Bigg( \frac{P_{k}}{P} \Bigg)^{-\rho} C\Bigg)^{\frac{\rho - 1}{\rho}} dk \Bigg)^{\frac{\rho}{\rho - 1}}\\
\implies
1 &= \Bigg( \int \Bigg( \frac{P_{k}}{P} \Bigg)^{1-\rho} dk \Bigg)^{\frac{\rho}{\rho - 1}}\\
\implies
1 &= P^{-\rho}\Bigg( \int P_k ^{1-\rho} dk \Bigg)^{\frac{\rho}{\rho - 1}}\\
\implies
P &= \Bigg(\int P_k^{1-\rho} dk \Bigg)^{\frac{1}{1-\rho}}
\end{align*}

FOC [$C_{ik}$]:

\begin{align*}
P_{ik} &=
P_k  \frac{\theta}{\theta - 1} \Bigg( \sum_{i=1}^{N_k} C_{ik}^{\frac{\theta - 1}{\theta}} \Bigg)^{\frac{\theta}{\theta - 1}-1} 
\frac{\theta - 1}{\theta} C_{ik}^{\frac{\theta - 1}{\theta}-1} \\
\implies
P_{ik} &=
P_k \Bigg( \sum_{i=1}^{N_k} C_{ik}^{\frac{\theta - 1}{\theta}} \Bigg)^{\frac{1}{\theta - 1}} 
C_{ik}^{\frac{ - 1}{\theta}} \\
\implies
P_{ik} &=
P_k C_k^{\frac{1}{\theta}} 
C_{ik}^{\frac{ - 1}{\theta}} \\
\implies
C_{ik} &=
\Bigg(\frac{P_{ik}}{P_{k}} \Bigg)^{-\theta}C_k
\end{align*}

\pagebreak

Substituting into the constraint, we get the sectoral price index in terms of the producers' prices:
\begin{align*}
C_k &= 
\Bigg( \sum_{i=1}^{N_k} \Bigg(\Bigg(\frac{P_{ik}}{P_{k}} \Bigg)^{-\theta}C_k\Bigg)^{\frac{\theta - 1}{\theta}} \Bigg)^{\frac{\theta}{\theta - 1}} \\
\implies
1 &= 
\sum_{i=1}^{N_k} P_{ik}^{1-\theta}P_{k}^{\theta-1}  \\
\implies
P_k &= 
\Bigg(\sum_{i=1}^{N_k} P_{ik}^{1-\theta}\Bigg)^{\frac{1}{1-\theta}}
\end{align*}

Thus, the aggregate price index $P$ as a function of producers’ prices is:

$$
P = \Bigg(\int \Bigg(\sum_{i=1}^{N_k} P_{ik}^{1-\theta}\Bigg)^{\frac{1-\rho}{1-\theta}} dk \Bigg)^{\frac{1}{1-\rho}}
$$

And optimal demand $C_{ik}$ as a function of producer's prices and aggregate demand is:

$$
C_{ik} =
\Bigg(\frac{P_{ik}}{P_{k}} \Bigg)^{-\theta}\Bigg( \frac{P_{k}}{P} \Bigg)^{-\rho} C
$$

2. Assume that firms compete a la Bertrand, i.e. choose $P_{ik}$ taking the prices of other firms in a sector $P_{jk}, j\neq i$ as given. Derive demand elasticity for a given firm and the optimal price.

We get rewrite demand for firm $i$ in sector $k$ as:

$$
C_{ik} = \frac{P_{ik}^{-\theta}}{P^{-\rho}}
\Bigg(\sum_{j=1}^{N_k} P_{jk}^{1-\theta}\Bigg)^{\frac{\theta - \rho}{1-\theta}}
C
$$

The demand elasticity for firm $i$ in sector $k$ is:

\begin{align*}
\frac{dC_{ik}/C_{ik}}{dP_{ik}/P_{ik}} 
&= \frac{C}{P^{-\rho}}\Bigg[
\frac{\theta - \rho}{1-\theta}\Bigg(\sum_{j=1}^{N_k} P_{jk}^{1-\theta}\Bigg)^{\frac{\theta - \rho}{1-\theta}-1} (1-\theta)P_{ik}^{-\theta} P_{ik}^{-\theta}+
\Bigg(\sum_{j=1}^{N_k} P_{jk}^{1-\theta}\Bigg)^{\frac{\theta - \rho}{1-\theta}}(-\theta)P_{ik}^{-\theta-1} \Bigg]
\frac{P_{ik}}{C_{ik}}\\
&= \frac{C}{P^{-\rho}}\Bigg[
(\theta - \rho)\Bigg(\sum_{j=1}^{N_k} P_{jk}^{1-\theta}\Bigg)^{\frac{2\theta - \rho - 1}{1-\theta}} P_{ik}^{-2\theta}
+
\Bigg(\sum_{j=1}^{N_k} P_{jk}^{1-\theta}\Bigg)^{\frac{\theta - \rho}{1-\theta}}(-\theta)P_{ik}^{-\theta-1} \Bigg]
\frac{P_{ik}}{C_{ik}}\\
&= \frac{C}{P^{-\rho}}\Bigg[
(\theta - \rho)P_k^{2\theta - \rho - 1} P_{ik}^{-2\theta}
-\theta P_k^{\theta - \rho}P_{ik}^{-\theta-1} \Bigg]
\frac{P_{ik}}{C_{ik}}\\
&= 
P_{ik}\frac{C}{P^{-\rho}}\Bigg[
(\theta - \rho)P_k^{2\theta - \rho - 1} P_{ik}^{-2\theta}
-\theta P_k^{\theta - \rho}P_{ik}^{-\theta-1} \Bigg]
\Bigg(\frac{P_{ik}}{P_{k}} \Bigg)^{\theta}\Bigg( \frac{P_{k}}{P} \Bigg)^{\rho} C^{-1}\\
&= 
\Bigg[
(\theta - \rho)P_k^{2\theta - \rho - 1} P_{ik}^{-2\theta}
-\theta P_k^{\theta - \rho}P_{ik}^{-\theta-1} \Bigg]
P_{ik}^{1+\theta}P_{k} ^{\rho-\theta} \\
&= 
(\theta - \rho)\Bigg(\frac{P_{ik}}{P_k}\Bigg)^{1-\theta}
-\theta
\end{align*}

The firms' problem is:

$$
\max_{P_{ik}} P_{ik}C_{ik} - W L_{ik}
$$
$$
\text{ s.t. } 
C_{ik} = A_{ik}L_{ik}
$$
$$
\text{ and }
C_{ik} =
\frac{P_{ik}^{-\theta}}{P^{-\rho}}
\Bigg(\sum_{j=1}^{N_k} P_{jk}^{1-\theta}\Bigg)^{\frac{\theta - \rho}{1-\theta}}
C
$$

$$
\implies
\max_{P_{ik}} 
P_{ik}  \frac{P_{ik}^{-\theta}}{P^{-\rho}}
\Bigg(\sum_{j=1}^{N_k} P_{jk}^{1-\theta}\Bigg)^{\frac{\theta - \rho}{1-\theta}}
C
- \frac{W}{A_{ik}}  \frac{P_{ik}^{-\theta}}{P^{-\rho}}
\Bigg(\sum_{j=1}^{N_k} P_{jk}^{1-\theta}\Bigg)^{\frac{\theta - \rho}{1-\theta}}
C
$$
$$
\implies
\max_{P_{ik}} P_{ik}^{1-\theta}
\Bigg(\sum_{j=1}^{N_k} P_{jk}^{1-\theta}\Bigg)^{\frac{\theta - \rho}{1-\theta}}
- \frac{W}{A_{ik}}  P_{ik}^{-\theta}
\Bigg(\sum_{j=1}^{N_k} P_{jk}^{1-\theta}\Bigg)^{\frac{\theta - \rho}{1-\theta}}
$$

FOC [$P_{ik}$]:

$$
(1-\theta)P_{ik}^{-\theta}
\Bigg(\sum_{j=1}^{N_k} P_{jk}^{1-\theta}\Bigg)^{\frac{\theta - \rho}{1-\theta}}
+
\frac{\theta - \rho}{1-\theta}
P_{ik}^{1-\theta}
\Bigg(\sum_{j=1}^{N_k} P_{jk}^{1-\theta}\Bigg)^{\frac{\theta - \rho}{1-\theta}-1}(1-\theta)P_{ik}^{-\theta}
$$

$$
= \frac{W}{A_{ik}}  
\Bigg[
(-\theta)
P_{ik}^{-\theta-1}
\Bigg(\sum_{j=1}^{N_k} P_{jk}^{1-\theta}\Bigg)^{\frac{\theta - \rho}{1-\theta}}
+ P_{ik}^{-\theta} \frac{\theta - \rho}{1-\theta}
\Bigg(\sum_{j=1}^{N_k} P_{jk}^{1-\theta}\Bigg)^{\frac{\theta - \rho}{1-\theta}-1}
(1-\theta)P_{ik}^{-\theta}
\Bigg]
$$

$$
(1-\theta)P_{ik}^{-\theta}
P_k^{\theta - \rho}
+
(\theta - \rho)
P_{ik}^{1-2\theta}
P_k^{2\theta - \rho-1}
= \frac{W}{A_{ik}}  
(-\theta)
P_{ik}^{-\theta-1}
P_k^{\theta - \rho}
+ \frac{W}{A_{ik}}  
(\theta - \rho)
P_{ik}^{-2\theta} 
P_k^{2\theta - \rho - 1}
$$

$$
(1-\theta)
+
(\theta - \rho)
P_{ik}^{1-\theta}
P_k^{\theta - 1}
= \frac{W}{A_{ik}}  
(-\theta)
P_{ik}^{-1}
+ \frac{W}{A_{ik}}  
(\theta - \rho)
P_{ik}^{-\theta} 
P_k^{\theta - 1}
$$


3. Prove that other things equal, firms with higher $A_{ik}$ set higher markups.

...

4. Assume that $\rho=1 , \theta= 5,N_k= 20$, and $\log A_{ik} \sim i.i.d. N(0,1)$. Solve the model numerically by approximating the number of sectors with $K= 100,000$. You will need an efficient algorithm to compute a sectoral equilibrium (search for a fixed point, do not use “solve”) nested in a general equilibrium loop solving for real wages.

...

5. Compute the aggregate output $C$ of the economy and compare it to the first-best value.

...

6. Bonus task: Does the sectoral equilibrium converge to the one under Betrand competition with homogeneous goods in the limit $\theta \to \infty$?

...

