---
title: "ECON 712 - PS 3"
author: "Alex von Hafften^[I worked on this problem set with a study group of Michael Nattinger, Andrew Smith, and Ryan Mather. I also discussed problems with Emily Case, Sarah Bass, and Danny Edgel.]"
date: "9/24/2020"
output: pdf_document
header-includes:
- \newcommand{\N}{\mathbb{N}}
- \newcommand{\Z}{\mathbb{Z}}
- \newcommand{\R}{\mathbb{R}}
- \newcommand{\Q}{\mathbb{Q}}
- \usepackage{bm}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

1. Consider the following overlapping generations problem. In each period $t = 1, 2, 3, ...$ a new generation of 2 period lived households are born.  Each generation has a unitary mass.  There is a unit measure of initial old who are endowed with $\bar{M} > 0$ units of fiat money. Each generation is endowed with $w_1$ in youth and $w_2$ in old age of non-storable consumption goods where $w_1 > w_2$.  There is no commitment technology to enforce trades. The utility function of a household of generation $t \ge 1$ is $U(c_t^t, c_{t+1}^t) = \ln(c_t^t) + \ln(c_{t+1}^t)$ where $(c_t^t, c_{t+1}^t)$ is consumption of a household of generation $t$ in youth (i.e., in period $t$) and old age (i.e., in period $t+1$).  The preference of the initial old are given by $U(c_1^0) = \ln(c_1^0)$ where $c_1^0$ is consumption by a household of the initial old.

(a) State and solve the planner problem.

In any period $t$, the social planner weights agents alive equally and optimally allocates resources between them given preferences and technologies:

\begin{align*}
\max_{(c_t^t, c_t^{t-1}) \in \R^2_+} & \ln(c_t^t) + \ln(c_{t}^{t-1})\\
\text{s.t. } c_t^t + c_t^{t-1} &\le w_1 + w_2
\end{align*}

Since utility is strictly increasing in consumption, we know that the maximum will occur at $c_t^t + c_t^{t-1} = w_1 + w_2 \implies c_t^{t-1} = w_1 + w_2 - c_t^t$. Thus, we can write the social planner's problem as an unconstrained maximization problem:

$$
\max_{c_t^t \in \R_+} \ln(c_t^t) + \ln(w_1 + w_2 - c_t^t)
$$

Setting the first order condition to zero:

$$
\frac{1}{c_t^t} - \frac{1}{w_1 + w_2 - c_t^t} = 0 \implies c_t^t  = \frac{w_1 + w_2}{2}
$$

Plugging the solution into the equation for the consumption of old agents:

$$
c_t^{t-1} = w_1 + w_2 - \frac{w_1 + w_2}{2} = \frac{w_1 + w_2}{2}
$$

Thus, the solution to the social planner's problem is $(c_t^t, c_t^{t-1}) = \Big(\frac{w_1 + w_2}{2}, \frac{w_1 + w_2}{2} \Big)$.

\pagebreak

(b) State the representative household's problem in period $t \ge 0$. Try to write the budget constraints in real terms.

I break the household problem into the problem facing an initial old agent and the problem facing agents born in period $t > 0$.  Let $p_t$ be the number of dollar per unit of consumption good in period $t$.  Define $M_{t+1}^t \in \R_+$ as the monetary holdings of the generation born in $t$ between periods $t$ and $t+1$.

The problem facing the initial old agents is:

\begin{align*}
\max_{c_1^0 \in \R_+} & \ln(c_1^0) \\
\text{s.t. } c_1^0 & \le w_2 + \frac{\bar{M}}{p_1}
\end{align*}

The problem facing agents born in period $t > 0$ is:

\begin{align*}
\max_{(c_t^t, c_{t+1}^t, M_{t+1}^t) \in \R^3_+} & \ln(c_t^t) + \ln(c_{t+1}^{t})\\
\text{s.t. } c_t^t & \le w_1 - \frac{M_{t+1}^t}{p_t}\\ 
             c_{t+1}^t & \le w_2 + \frac{M_{t+1}^t}{p_{t+1}} 
\end{align*}

(c) Define and solve for an autarkic equilibrium, assuming that it exists.

In an autarky, money has no value. Thus, agents do not forego consumption to hold money, or $M_{t+1}^t=0$ $\forall t$. Thus, in period 1, young agents do not trade with old agents because they believe that money will not be valued in period 2. Thus, the stock of fiat currency disappears with the death of the initial old agents.  

In an autarky, the problem facing the initial old agents collapses to:

\begin{align*}
\max_{c_1^0 \in \R_+} & \ln(c_1^0) \\
\text{s.t. } c_1^0 & \le w_2
\end{align*}

Trivially, $c_1^0 = w_2$.

In an autarky, the problem facing agents born in period $t > 0$ collapses to:

\begin{align*}
\max_{(c_t^t, c_{t+1}^t) \in \R^2_+} & \ln(c_t^t) + \ln(c_{t+1}^{t})\\
\text{s.t. } c_t^t & \le w_1\\ 
             c_{t+1}^t & \le w_2
\end{align*}

So, $(c_t^t, c_{t+1}^{t})=(w_1, w_2)$.  Thus, the autarkic equilibrium is $\{(w_1, w_2)\}_{\forall t}$.

\pagebreak

(d) Define and solve for a competitive equilibrium assuming valued money but with $w_2=0$.

A competitive equilibrium is the allocation $\{(c_t^t, c_t^{t-1}\}_{\forall t}$ and prices $\{p_t\}_{\forall t}$ such that agents optimize and markets clear:

\begin{align*}
c_t^t+c_t^{t-1} &= w_1 + w_2 & \text{(Goods Market)}\\
M_{t+1}^t &= \bar{M} & \text{(Money Market)}
\end{align*}

We can rewrite the problem of agents born in period $t > 0$ with $w_2 = 0$, since utility is strictly increasing in consumption.

$$
\max_{M_{t+1}^t \in \R_+} \ln\Bigg(w_1 - \frac{M_{t+1}^t}{p_t}\Bigg) + \ln\Bigg(\frac{M_{t+1}^t}{p_{t+1}}\Bigg)
$$

Setting the first order condition to zero:

\begin{align*}
\Bigg(w_1 - \frac{M_{t+1}^t}{p_t}\Bigg)^{-1} (-p_t)^{-1} + \Bigg(\frac{M_{t+1}^t}{p_{t+1}}\Bigg)^{-1} (p_{t+1})^{-1} &= 0 
\implies M_{t+1}^t = \frac{p_t w_1}{2} \\
\end{align*}

Plugging back in for $c_t^t$ and $c_{t+1}^t$:

\begin{align*}
c_t^t &= w_1 - \frac{(p_t w_1)/2}{p_t} = \frac{w_1}{2} \\
c_{t+1}^t &= \frac{(p_t w_1)/2}{p_{t+1}} = \Bigg(\frac{p_t}{p_{t+1}}\Bigg) \frac{w_1}{2}
\end{align*}

Setting $w_2=0$ and substituting in the household's optimization conditions, the goods market clearing condition becomes:

\begin{align*}
c_t^t + c_t^{t-1} &= w_1 + 0
\implies \frac{w_1}{2} + \Bigg(\frac{p_t}{p_{t+1}}\Bigg) \frac{w_1}{2} = w_1
\implies p_t = p_{t+1}
\end{align*}

The money market condition implies:

\begin{align*}
\frac{p_t w_1}{2} &= \bar{M}
\implies
p_t &= \frac{2\bar{M}}{w_1}
\end{align*}

Thus, the competitive equilibrium is the allocation $\Big\{\Big(\frac{w_1}{2}, \frac{w_1}{2} \Big)\Big\}_{\forall t}$ and prices $\Big\{\frac{2\bar{M}}{w_1}\Big\}_{\forall t}$

\pagebreak

(e) Compare the solutions to the planners problem, the autarky equilibrium and the stationary monetary competitive equilibrium with valued money, all with $w_2 = 0$.

(f) What happens to consumption, money demand and prices in a competitive equilibrium with valued money if the initial money supply is halved, i.e. $\bar{M}' = \frac{\bar{M}}{2}$. Keep the assumption that $w_2 = 0$.

2. Plot the trade offer curves for the following utility functions where the endowment is $(w_1, w_2)$ for goods 1 and 2, respectively.

(a) $U=10c_1-4c_1^2+4c_2-c_2^2, (w1, w_2) = (0, 2)$

(b) $U = \min{2c_1 + c_2, c_1 + 2c_2}, (w1, w_2) = (1, 0)$

(c) $U = \min{2c_1 + c_2, c_1 + 2c_2}, (w1, w_2) = (1, 10)$
