---
title: "ECON 712 - PS 4"
author: "Alex von Hafften^[I worked on this problem set with a study group of Michael Nattinger, Andrew Smith, and Ryan Mather. I also discussed problems with Emily Case, Sarah Bass, and Danny Edgel.]"
date: "10/1/2020"
output: pdf_document
header-includes:
- \newcommand{\N}{\mathbb{N}}
- \newcommand{\Z}{\mathbb{Z}}
- \newcommand{\R}{\mathbb{R}}
- \newcommand{\Q}{\mathbb{Q}}
- \usepackage{bm}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Consider the following overlapping generations problem. Each period $t=1, 2, 3, ...$ a new generation of 2 period lived households are born.  The measure of identical households born in any period grows by $1 + n$.  That is, we assume population growth of rate $n \ge 0$.

There is a unit measure of initial old who are endowed with $\bar{M_1}$ units of fiat money as well as $w_2$ units of consumption goods.  Instead of a fixed money supply, now assume that the money supply increases at the rate $z \ge 0$. The increase in money supply is handed out each period to old agents in direct proportion to the amount of money that they chose when young.  In other words, if a young agent chooses $M_{t+1}^t \ge 0$, they will receive $(1+z)M_{t+1}^t$ units of money when old.

Each generation is endowed with $w_1$ in youth and $w_2$ in old age of nonstorable consumption goods where $w_1 >w_2$. The utility function of a household of generation $t \ge 1$ is $U(c_t^t, c_{t+1}^t) = \ln(c_t^t) + \ln(c_{t+1}^t)$ where $(c_t^t, c_{t+1}^t)$ is consumption of a household of generation $t$ in youth (i.e., in period $t$) and old age (i.e., in period $t+1$). The preferences of the initial old are given by $U(c_0^t)=\ln(c_1^0)$, where $c_1^0$ is the consumption by a household of the initial old.

1. State and solve the planner's problem under the assumption of equal weights on each generation (i.e., on representative agents from each generation) so that the objective of the social planner is to maximize $U(c_1^0)+\sum_{t=1}^\infty U(c_t^t, c_{t+1}^t)$. Since this objective may not be well defined (i.e., add up to infinity), we can apply the "overtaking" criterion to determine optimality. Hence just go ahead and maximize away as usual.

The social planner maximizes utility by weighting each alive generations equally subject to resource feasibility:

\begin{align*}
\max_{c_1^0, c_i^i, c_{i+1}^{i} \in \R_+, i \in \N} & U(c_1^0)+\sum_{t=1}^\infty U(c_t^t, c_{t+1}^t)\\
\text{s.t. } & (1+n)c_t^t + c_t^{t-1} \le (1+n)w_1+w_2 \text{ } \forall t \in \N \\
\implies \max_{c_1^0, c_i^i, c_{i+1}^{i} \in \R_+, i \in \N} & \ln(c_1^0)+\sum_{t=1}^\infty \ln(c_t^t)+\sum_{t=1}^\infty \ln (c_{t+1}^t)\\
\text{s.t. } & c_t^{t-1} \le (1+n)w_1+w_2-(1+n)c_t^t \text{ }\forall t \in \N
\end{align*}

\pagebreak

Since consumption is increasing we know that the maximum will occur when the entire endowment is consumed, so we can substitute in $c_{t+1}^{t} = (1+n)w_1+w_2-(1+n)c_{t+1}^{t+1}$:

\begin{align*}
\max_{c_1^0, c_i^i \in \R_+, i \in \N} & \ln(c_1^0)+\sum_{t=1}^\infty \ln(c_t^t)+\sum_{t=1}^\infty \ln [(1+n)w_1+w_2-(1+n)c_{t+1}^{t+1}]\\
\implies \max_{c_1^0, c_i^i \in \R_+, i \in \N} & \ln(c_1^0)+\sum_{t=1}^\infty \ln(c_t^t)+\sum_{t=2}^\infty \ln [(1+n)w_1+w_2-(1+n)c_{t}^{t}]
\end{align*}

We can find the $c_t^t$ that overtakes all other allocations by setting the first order condition of the objective function with respect to $c_t^t$ to zero:

\begin{align*}
\frac{1}{c_t^t} - \frac{1+n}{(1+n)w_1+w_2-(1+n)c_t^t} &= 0 \\
\implies c_t^t &= \frac{1}{2}w_1 + \frac{1}{2(1+n)}w_2 \\
\implies c_t^{t-1} &= \frac{1+n}{2}w_1 + \frac{1}{2}w_2
\end{align*}

Thus, the solution to the social planner's problem is $\Bigg\{\Bigg(\frac{1}{2}w_1 + \frac{1}{2(1+n)}w_2, \frac{1+n}{2}w_1 + \frac{1}{2}w_2\Bigg)\Bigg\}_{\forall t>0}$ and $c_1^0=$

2. Let $p_t$ be the price of consumption goods in terms of money at time $t$. Define a competitive equilibrium.

A competitive equilibrium is an allocation and set of prices such that agents optimize and markets clear.

The problem of the initial old generation is

\begin{align*}
\max_{c_1^0 \in \R_+} & \ln(c_1^0)\\
\text{s.t. } & p_1c_1^0 \le p_1w_2 + \bar{M_1}
\end{align*}

The problem of generations $t > 0$ is

\begin{align*}
\max_{(c_t^t, c_{t+1}^t, M_{t+1}^t) \in \R_+^3} & \ln(c_t^t) + \ln(c_{t+1}^t)\\
\text{s.t. } & p_tc_t^t \le p_tw_1 - M_{t+1}^t\\
             & p_{t+1}c_{t+1}^t \le p_{t+1}w_2 + (1+z)M_{t+1}^t\\
\end{align*}

The market clearing conditions are

\begin{align*}
(1+n)c_t^t+c_t^{t-1} &\le (1+n)w_1+w_2                     & \text{(Goods Market)} \\
    (1+n)^tM_{t+1}^{t} &\le (1+z)^{t-1}\bar{M_1}           & \text{(Money Market)}
\end{align*}

\pagebreak

3. Solve for an autarkic equilibrium.

In autarky, $m_{t+1}^{t} = \frac{M_{t+1}^{t}}{p_t} = 0$. The problem of generations $t > 0$ collapses to

\begin{align*}
\max_{(c_t^t, c_{t+1}^t) \in \R_+^2} & \ln(c_t^t) + \ln(c_{t+1}^t)\\
\text{s.t. } & c_t^t \le w_1\\
             & c_{t+1}^t \le w_2\\
\end{align*}

So agents born in $t > 0$ consume $(c_t^t, c_{t+1}^t) = (w_1, w_2)$.  The initial old consume $w_2$ in period 1.  The goods market trivially clears: $(1+n)(w_1)+(w_2) = (1+n)w_1+w_2$.  And the money market clears by Walras' Law, so $M_{t+1}^{t} = \frac{(1+z)^{t-1}}{(1+n)^t}\bar{M_1}$ for all $t$.

4. Solve for a steady state (non-autarkic) monetary equilibrium.  As $w_1 > w_2$, we know this corresponds to the Samuelson case with $\beta = 1$. Verify the non-negativity constraint on money is not binding in the equilibrium.  What is the rate of return on money in the monetary equilibrium? Give intuition why the rate of return is at the level you find.

First, we solve for the initial old and generation $t$'s problems given goods prices $(p_t, p_{t+1})$ for $t \ge 1$.  Since utility is increasing in consumption, the agent will consume where the constraint at equality, so we can substitute $c_t^t = w_1 - \frac{M_{t+1}^t}{p_t}$ and $c_{t+1}^t = w_2 + (1+z)\frac{M_{t+1}^t}{p_{t+1}}$:

$$
\max_{M_{t+1}^t \in \R_+} \ln\Bigg(w_1 - \frac{M_{t+1}^t}{p_t}\Bigg) + \ln\Bigg( w_2 + (1+z)\frac{M_{t+1}^t}{p_{t+1}} \Bigg)
$$

Setting the first order condition to zero:

\begin{align*}
0 &= \Bigg(w_1 - \frac{M_{t+1}^t}{p_t}\Bigg)^{-1} \Bigg( \frac{-1}{p_t} \Bigg) + \Bigg( w_2 + \frac{(1+z)M_{t+1}^t}{p_{t+1}} \Bigg)^{-1}\Bigg(\frac{1+z}{p_{t+1}}\Bigg) \\
M_{t+1}^t &= \frac{p_t}{2}w_1 - \frac{p_{t+1}}{2(1+z)}w_2 \\
c_t^t &= w_1 - \frac{1}{p_t} \Bigg( \frac{p_t}{2}w_1 - \frac{p_{t+1}}{2(1+z)}w_2 \Bigg) \\
      &= \frac{1}{2}w_1 + \frac{p_{t+1}}{2(1+z)p_t}w_2\\
c_{t+1}^t &= w_2 + \frac{1+z}{p_{t+1}}\Bigg( \frac{p_t}{2}w_1 - \frac{p_{t+1}}{2(1+z)}w_2 \Bigg)\\
          &= \frac{1}{2}w_2 + \frac{(1+z)p_t}{2p_{t+1}}w_1 
\end{align*}

\pagebreak

With $q_t = \frac{p_t}{p_{t+1}}$, the goods market clearing (at equality) implies the following first-order difference equation:

\begin{align*}
(1+n)\Bigg(\frac{1}{2}w_1 + \frac{1}{2(1+z)q_t}w_2\Bigg) + \Bigg( \frac{1}{2}w_2 + \frac{(1+z)q_{t-1}}{2}w_1 \Bigg) &= (1+n)w_1+w_2 \\
q_t &= \frac{(1+n)w_2}{(1+z)[(1+n)w_1+w_2 -(1+z)w_1q_{t-1}]}
\end{align*}

Solving for steady states $\bar{q}=q_t = q_{t-1}$:

\begin{align*}
\bar{q} &= \frac{(1+n)w_2}{(1+z)[(1+n)w_1+w_2 -(1+z)w_1\bar{q}]} \\
\implies 0 &= (1+z)w_1\bar{q}^2 - [(1+n)w_1+w_2]\bar{q} + \frac{(1+n)w_2}{(1+z)} \\
\implies \bar{q} &= \frac{[(1+n)w_1+w_2] \pm \sqrt{[(1+n)w_1+w_2]^2 - 4(1+z)w_1\frac{(1+n)w_2}{(1+z)}}}{2(1+z)w_1} \\
\implies \bar{q} &= \frac{(1+n)w_1+w_2 \pm [(1+n)w_1 - w_2]}{2(1+z)w_1} \\
\implies \bar{q} &= \frac{ w_2}{(1+z)w_1} \text{  or  }  \bar{q} = \frac{(1+n)}{(1+z)} 
\end{align*}

The first steady state $\bar{q} = \frac{ w_2}{(1+z)w_1}$ corresponds to autarky:

\begin{align*}
c_t^t &= \frac{1}{2}w_1 + \frac{(1+z)w_1}{2(1+z)w_2}w_2 = w_1 \\
c_{t+1}^t &= \frac{1}{2}w_2 + \frac{(1+z)w_2}{2(1+z)w_1}w_1 = w_2
\end{align*}

The second steady state $\bar{q} = \frac{(1+n)}{(1+z)}$ corresponds to a steady state monetary equilibrium with inter-generation trade:

\begin{align*}
c_t^t &= \frac{1}{2}w_1 + \frac{(1+z)}{2(1+z)(1+n)}w_2 \\
&= \frac{1}{2}w_1 + \frac{1}{2(1+n)}w_2  \\
c_{t+1}^t &=  \frac{1}{2}w_2 + \frac{(1+z)(1+n)}{2(1+z)}w_1 \\
&= \frac{1+n}{2}w_1 + \frac{1}{2}w_2
\end{align*}

Since $w_1 > w_2 \implies w_1 > \frac{1+n}{2}w_1+\frac{1}{2}w_2  > \frac{1}{2}w_1+\frac{1}{2(1+n)}w_2 > w_2$ with $1+n>1$, so agents are saving to consume more when they are old instead of borrowing to consume more when young.  Thus, the non-negativity constraint on money is not binding in the steady state monetary equilibrium. 

\pagebreak

To solve for prices, first the household budget constraint implies the level of money holdings:

\begin{align*}
\frac{1}{2}w_1 + \frac{1}{2(1+n)}w_2  &= w_1 - \frac{M_{t+1}^t}{p_t} \\
 M_{t+1}^t  &= p_t\Bigg(\frac{(1+n)w_1-w_2}{2(1+n)}\Bigg)\\
\end{align*}

And the money market clearing condition implies that prices are 

\begin{align*}
p_t\Bigg(\frac{(1+n)w_1-w_2}{2(1+n)}\Bigg) &= \frac{(1+z)^{t-1}\bar{M_1}}{(1+n)^t } \\
p_t  &= \frac{(1+z)^{t-1}2\bar{M_1}}{(1+n)^{t-1} ((1+n)w_1-w_2)}
\end{align*}

Thus, the representative agent in the initial old generation consumes 

$$
c_1^0 = w_2 + \bar{M_1}/p_t = w_1 + \frac{2\bar{M_1}^2}{ (1+n)w_1-w_2}.
$$

From the household budget constraint, we know that the nominal rate of return on money is 

$$\frac{(1+z)M_{t+1}^t - M_{t+1}^t}{M_{t+1}^t}=z$$

because the money holding grows by $z+1$ between the periods. The real value of money in $t$ is $M_{t+1}^t/p_t$ and the real value of money in $t+1$ is $(1+z)M_{t+1}^t/p_{t+1}$, so the real rate of return on money at equilibrium is 

$$\frac{(1+z)M_{t+1}^t/p_{t+1} - M_{t+1}^t/p_t}{M_{t+1}^t/p_t} = (1+z)\bar{q}-1 = (1+z)\frac{(1+n)}{(1+z)} -1 = n.$$

This real rate of return makes sense because at the steady state in each period the old consume the same proportion of the goods market, so the real value of their money needs to grow at the same rate as the goods market. The size of the goods market in $t$ is $(n+1)^{t}w_1 + (n+1)^{t-1}w_2$ and in $t+1$ it is $(n+1)^{t+1}w_1 + (n+1)^{t}w_2$, so the rate of growth of the goods market is $n$:

\begin{align*}
& \frac{[(n+1)^{t+1}w_1 + (n+1)^{t}w_2]-[(n+1)^{t}w_1 + (n+1)^{t-1}w_2]}{(n+1)^{t}w_1 + (n+1)^{t-1}w_2}\\
= &\frac{[(n+1)^{t+1} - (n+1)^{t}] w_1 + [(n+1)^{t}-(n+1)^{t-1}]w_2}{(n+1)^{t}w_1 + (n+1)^{t-1}w_2}\\
= & \frac{(n+1-1)(n+1)^{t} w_1 + (n+1-1)(n+1)^{t-1}w_2}{(n+1)^{t}w_1 + (n+1)^{t-1}w_2}\\
= & n \frac{(n+1)^{t} w_1 + (n+1)^{t-1}w_2}{(n+1)^{t}w_1 + (n+1)^{t-1}w_2}\\
= & n \\
\end{align*}

\pagebreak

5. Does the stationary monetary equilibrium Pareto dominate autarky? Can you use your answer in part 1 to establish that? If so, how can the government implement it?

The allocation from the stationary monetary equilibrium is equivalent to the allocation in the solution to the planner's problem, which is the Pareto optimal allocation, thus the stationary monetary equilibrium is Pareto optimal.  Furthermore, a representative household in the initial old generation prefers the monetary equilibrium over autarky because she consumes more:

$$
\ln(w_2) > \ln\Bigg( w_1 + \frac{2\bar{M_1}^2}{ (1+n)w_1-w_2}\Bigg)
$$

because $w_1>w_2 \implies \frac{2\bar{M_1}^2}{ (1+n)w_1-w_2}>0$.

For the other generations, the stationary monetary equilibrium is preferred to autarky because of the strict concavity of the log utility function:

\begin{align*}
& \ln\Bigg(\frac{1}{2}w_1 + \frac{1}{2(1+n)}w_2\Bigg) + \ln\Bigg(\frac{1+n}{2}w_1 + \frac{1}{2}w_2\Bigg) \\
&= \ln\Bigg(\Bigg( \frac{n+2}{2n+2} \Bigg)\Bigg(\frac{n+1}{n+2}w_1 + \frac{1}{2+n}w_2\Bigg)\Bigg) + \ln\Bigg(\Bigg( \frac{n+2}{2}  \Bigg)\Bigg(\frac{1+n}{n+2}w_1 + \frac{1}{n+2}w_2\Bigg)\Bigg) \\
&= \ln\Bigg( \frac{n+2}{2n+2} \Bigg)+\ln\Bigg(\frac{n+1}{n+2}w_1 + \frac{1}{2+n}w_2\Bigg) + \ln\Bigg( \frac{n+2}{2}  \Bigg) + \ln \Bigg(\frac{1+n}{n+2}w_1 + \frac{1}{n+2}w_2\Bigg)\\
&= \ln\Bigg( \frac{(n+2)^2}{4n+4}\Bigg)+2\ln\Bigg(\frac{n+1}{n+2}w_1 + \frac{1}{n+2}w_2\Bigg)\\
&> \ln\Bigg( \frac{(n+2)^2}{4n+4}\Bigg)+\frac{2n+2}{n+2}\ln(w_1) + \frac{2}{n+2}\ln(w_2)\\
&> \ln(w_1) + \ln(w_2)
\end{align*}

The government implement the stationary monetary equilibrium by setting the price in period 1 to be on the equilibrium path: $p_1 = \frac{2\bar{M_1}}{ (1+n)w_1-w_2}$.

6. Does money exhibit super-neutrality?

Yes, money exbihits super-neutrality.  As I found in 4, the equilibrium consumption allocations do not depend on inflation. The equilibrium consumption allocations depend on population growth and the sizes of the endowments.