---
title: "ECON 711 - PS 7"
author: "Alex von Hafften^[I worked on this problem set with a study group of Michael Nattinger, Andrew Smith, Tyler Welch, and Ryan Mather. I also discussed problems with Emily Case, Sarah Bass, and Danny Edgel.]"
date: "10/25/2020"
output: pdf_document
header-includes:
- \newcommand{\N}{\mathbb{N}}
- \newcommand{\Z}{\mathbb{Z}}
- \newcommand{\R}{\mathbb{R}}
- \newcommand{\Q}{\mathbb{Q}}
- \newcommand{\Lf}{\mathcal{L}}
- \usepackage{bm}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# A Risky Investment

You have wealth $w > 0$ and preferences over lotteries represented by a von Neumann-Morgenstern expected utility function with Bernoulli utility $u$ which is strictly increasing, twice differentiable, and weakly concave.  Your friend wants you to invest in his startup; you can choose any amount $a \le w$ to invest, and your investment will either triple in value (with probability $p$) or become worthless (with probability $1-p$).  Your expected utility if you invest $a$ is therefore

$$
U(a) = pu(w-a+3a) + (1-p)u(w-a) = pu(w+2a) + (1-p)u(w-a)
$$

(a) Show that if $u$ is linear, then you invest all your wealth if $p > \frac{1}{3}$ and nothing if $p < \frac{1}{3}$.

If $u$ is linear and strictly increasing, $u$ can be represented as $u(x) = mx+b$ for some $m \in \R_{++}, b \in \R$:

\begin{align*}
U(a) 
&= pu(w+2a) + (1-p)u(w-a) \\
&= p(m(w+2a)+b) + (1-p)(m(w-a)+b) \\
&= pwm + 2pam + pb + wm - pwm - am + pam + b - pb \\
&= (3p - 1)ma + mw + b \\
\end{align*}

If $p > \frac{1}{3} \implies 3p-1 > 0$, so the coefficent on $a$ in utility function is positive. Thus, to maximize $U$, you want to invest as much as possible, which is all your wealth.  If $p < \frac{1}{3} \implies 3p-1 < 0$, so the coefficent on $a$ in utility function is negative. Thus, to maximize $U$, you want to invest as little as possible, which is nothing.

From here on, assume $p > \frac{1}{3}$, so the expected value of the investment is positive; and assume that you are strictly risk-averse ($u''< 0$).

(b) Show that it's optimal to invest a strictly positive amount.\footnote{You can do this by showing that $U'(0)>0$ - the marginal expected utility of increasing $a$ is positive when $a=0$.}

$$
U'(a) = pu'(w+2a)(2) + (1-p)u'(w-a)(-1) = 2pu'(w+2a) - (1-p)u'(w-a)
$$

$$
U'(0) = 2pu'(w+2(0)) - (1-p)u'(w-(0)) = 2pu'(w) - (1-p)u'(w) = (3p-1)u'(w)
$$

$U'(0) > 0$ because $3p-1 > 0$ and $u'(w) > 0$.

\pagebreak

(c) Show that $U(a)$ is strictly concave in $a$, so that except at a corner solution, the first-order condition is necessary and sufficient to find $a^*$.

$U(a)$ is strictly concave in $a$ iff $U(ta+(1-t)b) < tU(a)+(1-t)U(b)$ for $a, b \in [0, w]$ and $t \in [0, 1]$.  Because $u'' < 0$,

\begin{align*}
U(ta+(1-t)b) 
&= pu(w + 2(ta + (1-t)b)) + (1-p)u(w-(ta+(1-t)b)) \\
&= pu(t(w + 2a) + (1-t)(w + 2b)) + (1-p)u(t(w-a)+(1-t)(w-b)) \\
&< p(tu(w + 2a) + (1-t)u(w + 2b)) + (1-p)(tu(w-a)+(1-t)u(w-b)) \\
&= t ( pu(w + 2a) +(1-p) u(w-a)) + (1-t)(pu(w + 2b) + (1-p)u(w-b)) \\
&= t U(a) + (1-t)U(b)
\end{align*}

(d) Show that if $u'(0)$ is infinite, it's not optimal to invest all your wealth; and that if $u'(0)$ is finite, then there's a cutoff $\bar{p}$ such that it's optimal to invest all of your wealth if $p \ge \bar{p}$.

From (c), we know that the first-order condition is necessary and sufficient to find $a^*$.  The derivative of the utility function at $a=w$ is

$$
U'(w) = 2pu'(w+2(w)) - (1-p)u'(w-(w)) = 2pu'(3w) - (1-p)u'(0) 
$$

Thus, if $u'(0)$ is infinite, $U'(w) = -\infty$, so the first order condition cannot hold at $w$.

If $u'(0)$ is finite, the first order condition is:

$$
0 = 2\bar{p}u'(3w) - (1-\bar{p})u'(0) \implies \bar{p} = \frac{u'(0)}{2u'(3w)+u'(0)}
$$

Thus, if $p \ge \bar{p}$ investing all of your wealth is optimal.

From here on, assume that either $u'(0)$ is infinite or $p \in (\frac{1}{3}, \bar{p})$, so the optimal level of investment $a^*$ is strictly positive but below $w$.

(e) Show that if $u(x) = 1 - e^{-cx}$ (the Constant Absolute Risk Aversion or CARA utility function), your optimal investment $a^*$ does not depend on $w$.

(f) For general $u$, show that if your Coefficient of Absolute Risk Aversion $A(x) = -\frac{u''(x)}{u'(x)}$ is decreasing, you invest more as $w$ increases.

Now reframe the question as deciding what fraction $t$ of your wealth to invest; writing $a = tw$,

$$
U(t) = pu(w(1+2t)) + (1-p)u(w(1-t))
$$

(g) Show that if $u(x) = \frac{1}{1-\rho} x^{1-\rho}$, with $\rho \le 1$ and $\rho \neq 0$ (the Constant Relative Risk Aversion or CRRA utility function), you invest the same fraction of your wealth regardless of $w$.

(h) For general $u$, show that if your Coefficient of Relative Risk Aversion $R(x) = -\frac{xu''(x)}{xu'(x)}$ is increasing, you invest a smaller fraction of your wealth as $w$ increases.