---
title: "ECON 713B - Problem Set 3"
author: "Alex von Hafften^[This problem set is for ECON 713B Microeconomic Theory taught by Marzena Rostek with assistance from Arseniy Stolyarov at UW-Madison. I worked on this problem set with a study group of Michael Nattinger, Andrew Smith, and Ryan Mather. I also discussed problems with Sarah Bass, Emily Case, Danny Edgel, and Katherine Kwok.]"
date: "4/25/2021"
output:
 pdf_document: default
 html_document:
 df_print: paged
header-includes:
- \newcommand{\N}{\mathbb{N}}
- \newcommand{\Z}{\mathbb{Z}}
- \newcommand{\R}{\mathbb{R}}
- \newcommand{\Q}{\mathbb{Q}}
- \newcommand{\Lf}{\mathcal{L}}
- \usepackage{bm}
- \usepackage{bbm}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
```

## Problem 1

A risk-neutral principal hires an agent to work on a project, offering a wage of $w$. The agent exerts effort $e$. The agent’s utility function is $v(w,e) =\sqrt w-g(e)$, where $g(e)$ is the disutility associated with effort $e$. The agent can choose one of two possible effort levels, $e_1$ or $e_2$, with associated disutility levels $g(e_1) = 1$ and $g(e_2) =\frac{1}{2}$. If the agent chooses effort level $e_1$, the project yields an output of 8 for the principal with probability $\frac{1}{2}$ and 0 with probability $\frac{1}{2}$. If he chooses $e_2$, the project yields an output of 8 with probability $\frac{1}{4}$ and 0 with probability $\frac{3}{4}$. The agent’s reservation utility is 0.

(a) Suppose the effort level chosen by the agent is observable by the principal. A wage contract then specifies an effort level ($e_1$ or $e_2$) and an output-contingent wage schedule $\{w_H,w_L\}$. Here $w_H$ is the wage paid if the project yields 8, and $w_L$ is the wage paid if the project yields 0. If effort is observable, it is optimal for the principal to choose a fixed wage contract (that is, set $w_H=w_L$) for each effort level. Informally, explain the intuition for this result.

The principal wants the agent to put in high effort because the probability of the high output outcome is higher.  If effort is observable, then the principal can directly map high effort to a better outcome for the agent, so that the agent always puts in high effort.  Since the agent is risk-averse conditioning on output would change the agent's behavior.

(b) If effort is observable, which effort level should the principal implement? What is the principal's optimal wage contract?

If effort is observable, the principal should offer contracts that implement high effort because it increases the probability of a high output outcome.  Thus, the principal should offer wages for low effort $w_H(e_2) = w_L(e_2) = w(e_2)$ that result in negative utility:

$$
v(w(e_2),e_2) < 0 \implies \sqrt {w(e_2)}-g(e_2) < 0 \implies w(e_2) < \frac{1}{4}
$$

If we assume that the agent puts in high effort when they are indifferent between putting in high effort and not participating, then high effort wage is $w_H(e_1) = w_L(e_1) = w(e_1)$:

$$
v(w(e_1),e_1) = 0 \implies \sqrt {w(e_1)} - g(e_1) = 0 \implies \sqrt {w(e_1)} - 1 = 0 \implies w(e_1) = 1
$$

The expected profit for the principal under this wage scheme is: $\frac{1}{2}(8-1) + \frac{1}{2}(0-1) = 3$.

\pagebreak

(c) If effort is not observable, which effort level should the principal implement? What is the principal's optimal wage contract?

The principal should still implement high effort. Let $w_H$ and $w_L$ be the wages associated with high and low output. The expected utility of the agent putting in high effort is:

$$
\frac{\sqrt{w_H}}{2} + \frac{\sqrt{w_L}}{2} - 1
$$

The expected utility of the agent putting in low effort is:

$$
\frac{\sqrt{w_H}}{4} + \frac{3\sqrt{w_L}}{4} - \frac{1}{2}
$$

Since the principal seeks to maximize her expected profit, she pays the lowest wages to incentive the agent to put in high effort.  Thus, the individual rationality and incentive compatibility constraint hold with equality.  The individual rationality constraint implies:

$$
\frac{\sqrt{w_H}}{2} + \frac{\sqrt{w_L}}{2} - 1 = 0 \implies \sqrt{w_L} = 2 -\sqrt{w_H}
$$

The incentive compatibility constraint implies:

$$
\frac{\sqrt{w_H}}{2} + \frac{\sqrt{w_L}}{2} - 1 = \frac{\sqrt{w_H}}{4} + \frac{3\sqrt{w_L}}{4} - \frac{1}{2} 
\implies 
\sqrt{w_L} = \sqrt{w_H} - 2
$$

Therefore,

$$
2 -\sqrt{w_H} = \sqrt{w_H} - 2 \implies w_H = 4 \implies w_L = 0
$$

The expected profit for the principal under this wage scheme is: $\frac{1}{2}(8-4) + \frac{1}{2}(0-0) = 2$.

\pagebreak

## Problem 2

Consider a cashless entrepreneur who wants to borrow and carry out the following project. If he exerts an effort level of $e_1$, he will produce an output of $z$ with probability $P_1>0$ and 0 with probability $1-P_1$. If he exerts an effort level of $e_2$ he will produce an output of $z$ with probability $P_2$ ($P_2 < P_1$) and 0 with probability $1-P_2$. Let $c_1>0$ be the cost of effort $e_1$ for the entrepreneur and $c_2= 0$ be the cost of low effort $e_2$. A monopolistic bank with a cost of fund of $r$ offers a loan of 1 unit for a reimbursement of $z-x$ when the project is successful, where $x$ is the share of output retained by the agent. Let the entrepreneur’s utility with no project be 0. Assume $P_2 z < r$.

Determine the optimal loan contract of a bank which maximizes its expected profit subject to the incentive and participation constraints of the entrepreneur.

Notice that the expected level of output with low effort is insufficient to cover the bank's cost of funds even if the entrepreneur gets nothing, so the bank will never design a contract that incentives low effort.  The bank seeks to implement a high level of effort if its expected profit is positive; I provide such a condition at the end. If the entrepreneur exerts effort level $e_1$, her expected payoff is: $xP_1 - c_1$. If the entrepreneur exerts effort level $e_2$, her expected payoff is: $xP_2$. The participation constraint implies:

$$
xP_1 - c_1 \ge 0 \implies x \ge \frac{c_1}{P_1}
$$

The incentive compatibility constraint implies:

$$
xP_1 - c_1 \ge xP_2 \implies x \ge  \frac{c_1}{P_1 - P_2}
$$

Notice that if the incentive compatibility constraint holds then the participation constraint holds. The bank wants to maximize its expected profits, so it chooses the smallest $x$ to incentive high effort, so:

$$
x =  \frac{c_1}{P_1 - P_2}
$$

Therefore, the bank offers this contract if its expected profit is positive (otherwise it would not offer the contract):

$$
P_1\Bigg(z - \frac{c_1}{P_1 - P_2}\Bigg) - r > 0
$$

\pagebreak

## Problem 3

Consider a monopolist producing a good of quality $q$.  The quality can be either high ($q = 1$; then, the marginal cost of production is $c_1 > 0$) or low ($q = 0$; then, the marginal cost is $c_0 = 0$). There is a mass one of identical consumers. Each consumer’s payoff from purchasing one unit of a good with quality $q$ at price $p$ is $U = q - p$. Assume $c_1 < 1$ so that producing the high quality good is socially efficient.

(a) Suppose that consumers do not observe the good’s quality before purchasing it. The timing of the game is as follows:

i. The monopolist chooses the quality of the good;
ii. The monopolist chooses the price;
iii. Consumers observe the price (but not the quality) and decide whether to buy (one unit of) the good.

Find a pure-strategy PBE of the game.

Consider a pure-strategy PBE of the game where the monopolist produces $q=0$, charges some price $p > 0$, consumers do not purchase the good, and consumers believe that $q=0$ with certainty regardless of the price charged.  The monopolist have no incentive to deviate to $q=1$ because no matter what price is charged consumer don't buy.  Consumers have no incentive to deviate because purchasing the good will result in negative utility: $U = 0 - p < 0$. Thus, this is a pure-strategy PBE.

(b) Suppose now that a proportion $\alpha$ of the consumers can observe the good’s quality before purchasing it. The remaining $1 - \alpha$ consumers observe product quality only after the purchase.  The timing of the game is modified in the third stage: the informed consumers observe $q$ and the price and decide whether to buy the good, while the uninformed consumers only observe the price and decide whether to buy. Find a pure-strategy equilibrium of the game, in which all consumers buy a high-quality good.

In this equilibrium, we know that the monopolist chooses $q=1$ and all consumers buy the high-quality good.  This implies that the uninformed consumers must believe that $q=1$ with certainty after observing $p$.  Thus, they are willing to pay up to $p = 1$.  Informed consumers only buy (at a positive price) if $q=1$ and similarly are willing to pay up to $p=1$.  Thus, the profit-maximizing price for the monopolist is $p = 1$ and their profit is $\pi_{q=1} = 1 - c_1$.

If the monopolist chooses $q=0$ instead, the informed consumers do not buy, but $p=1$ is still the profit-maximizing price for serving the uninformed market.  Thus, the monopolist's profit is $\pi_{q=0} = 1 - \alpha$.  Thus, for a pure-strategy equilibrium where all consumers buy high-quality goods to exist:

$$
\pi_{q=1} \ge \pi_{q=0} \implies 1 - c_1 \ge 1 - \alpha \implies \alpha \ge c_1
$$