---
title: "ECON 709 - PS 1"
author: "Alex von Hafften^[I worked on this problem set with a study group of Michael Nattinger, Andrew Smith, and Ryan Mather. I also discussed problems with Emily Case, Sarah Bass, and Danny Edgel.]"
date: "9/14/2020"
output: pdf_document
header-includes:
- \newcommand{\N}{\mathbb{N}}
- \newcommand{\Z}{\mathbb{Z}}
- \newcommand{\R}{\mathbb{R}}
- \newcommand{\Q}{\mathbb{Q}}
- \usepackage{bm}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

1.  Suppose that $Y = X^3$ and $f_X(x)=42x^5(1-x), x \in (0,1)$.  Find the PDF of $Y$, and show that the PDF integrates to 1.

Notice that $Y = X^3$ is a monotone transformation, so we can use the following theorem from the lecture notes:

\begin{align*}
f_Y(y) 
&= \begin{cases} f_X(g^{-1}(y))|\frac{d}{dy}g^{-1}(y)|, y \in Y \\  0, \text{ otherwise} \end{cases} \\
&= \begin{cases} 42(y^{1/3})^5 (1-y^{1/3})|(1/3)y^{-2/3}|, y \in (0, 1) \\  0, \text{ otherwise} \end{cases} \\
&= \begin{cases} 14y(1-y^{1/3}), y \in (0, 1) \\ 0, \text{ otherwise} \end{cases}
\end{align*}

where $g^{-1}(y) = y^{1/3}$ and $Y=\{0^3, 1^3\}=\{0, 1\}$.

$f_Y(y)$ integrates to 1:

\begin{align*}
\int_0^1 14t(1-t^{1/3})dt 
&= 14\Bigg[y^2/2 - \frac{y^{7/3}}{7/3}\Bigg]_0^1\\
&= 14\Bigg[\frac{1}{2} - \frac{3}{7}\Bigg]\\
&= 1
\end{align*}

\pagebreak

2. For the following CDF and PDF, show that $f_X$ is the density function of $F_X$ as long as $a \ge 0$.  That is, show that for all $x \in [0, 1], F_X(x)=\int_0^xf_X(t)dt$.

\begin{align*}
F_X(x) &= \begin{cases} 1.2x, x \in [0,0.5) \\ 0.2+0.8x, x \in [0.5,1] \end{cases} \\
f_X(x) &= \begin{cases} 1.2, x \in [0, 0.5) \\ a, x = 0.5 \\ 0.8, x \in (0.5, 1] \end{cases}
\end{align*}

Case 1: $x < 0.5$

\begin{align*}
\int_0^x f_X(t) dt &= \int_0^x 1.2 dt \\
&= 1.2x \\
&= F_X(x)
\end{align*}

Case 2: $x = 0.5$

\begin{align*}
\int_0^x f_X(t) dt &= \int_0^{0.5} 1.2 dt + \int_{0.5}^{0.5} a dt \\
&= 1.2(0.5) + 0 \\
&= 0.6 \\
&= 0.2 + 0.8 (0.5) \\
&= F_X(0.5)
\end{align*}

Case 3: $x > 0.5$

\begin{align*}
\int_0^x f_X(t) dt &= \int_0^{0.5} 1.2 dt + \int_{0.5}^{0.5} a dt + \int_{0.5}^x 0.8 dt \\
&= 1.2 (0.5) + 0 + 0.8x - 0.8(0.5) \\
&= 0.6 + 0.8x - 0.4 \\
&= 0.2 + 0.8x \\
&= F_X(x)
\end{align*}

\pagebreak

3. Let $X$ have PDF $f_X(x) = \frac{2}{9}(x+1), x\in[-1, 2]$.  Find the PDF of $Y=X^2$.

For $x \in [-1, 2]$

\begin{align*}
F_X(x) 
&= \int_{-1}^x \frac{2}{9}(t+1)dt \\
&= \frac{2}{9}\Bigg[\frac{t^2}{2}+t\Bigg]_{-1}^x \\
&= \frac{2}{9}\Bigg[\frac{x^2}{2}+x - \Bigg(\frac{1}{2}-1\Bigg)\Bigg] \\
&= \frac{x^2}{9} + \frac{2x}{9} + \frac{1}{9}
\end{align*}

Thus,

\begin{align*}
F_X(x) 
= \begin{cases} 
       0, & x < -1 \\
       \frac{x^2}{9} + \frac{2x}{9} + \frac{1}{9}, & x \in [-1, 2] \\
       1, & x > 2 
    \end{cases}
\end{align*}

Consider $Y=X^2$. First, notice that $y \in [0, 4]$.  I consider two cases $y \in [0, 1]$ and $y \in (1, 4]$

Case 1: $y \in [0, 1]$

\begin{align*}
F_Y(y) 
&= P(Y \le y) \\
&= P(X^2 \le y) \\
&= P(-\sqrt{y} \le X \le \sqrt{y}) \\
&= P(X \le \sqrt{y}) - P(X \le -\sqrt{y}) \\
&= F_X(\sqrt{y}) - F_X(-\sqrt{y}) \\
&= \Bigg[ \frac{y}{9} + \frac{2\sqrt{y}}{9} + \frac{1}{9} \Bigg] - \Bigg[ \frac{y}{9} - \frac{2\sqrt{y}}{9} + \frac{1}{9} \Bigg] \\
&= \frac{4\sqrt{y}}{9} \\
\end{align*}

Case 2: $y \in (1, 4]$

\begin{align*}
F_Y(y) 
&= P(Y \le y) \\
&= P(X^2 \le y) \\
&= P(X \le \sqrt{y}) \\
&= F_X(\sqrt{y}) \\
&= \frac{y}{9} + \frac{2\sqrt{y}}{9} + \frac{1}{9}
\end{align*}

Thus, the CDF and PDF of $Y$ is:

\begin{align*}
F_X(x) 
= \begin{cases} 
       0, & y < 0 \\
       \frac{4\sqrt{y}}{9}, & y \in [0, 1] \\
       \frac{y}{9} + \frac{2\sqrt{y}}{9} + \frac{1}{9}, & y \in (1, 4] \\
       1, & y > 4 
    \end{cases}
\end{align*}

\begin{align*}
f_X(x) 
= \begin{cases} 
       \frac{2}{0\sqrt{y}}, & y \in [0, 1] \\
       \frac{1}{9} + \frac{1}{9\sqrt{y}}, & y \in (1, 4] \\
       0, & \text{ otherwise.} 
    \end{cases}
\end{align*}

4.  A median of a distribution is a value $m$ such that $P(X \le m) \ge 1/2$ and $P(X \ge m) \ge 1/2$. Find the median of the distribution $f(x) = \frac{1}{\pi(1+x^2)}, x \in \R$. 

The CDF of $X$ is

\begin{align*}
F(x) &= \int_{-\infty}^x \frac{1}{\pi(1+t^2)} dt  \\
&= \frac{1}{\pi}  \int_{-\infty}^x \frac{1}{1+t^2} dt  \\
&= \frac{1}{\pi}  \Bigg[ \tan^{-1}(t) \Bigg]_{-\infty}^x  \\
&= \frac{1}{\pi}  \Bigg[ \tan^{-1}(x) - \lim_{t \to -\infty} \tan^{-1}(t)  \Bigg]  \\
&= \frac{1}{\pi}  \Bigg[ \tan^{-1}(x) - \frac{\pi}{2} \Bigg]  \\
\end{align*}

Now, notice that the distribution is symmetric around 0, so we will consider $m=0$

\begin{align*}
P(X \le 0) 
&= F(0) \\
&= \frac{1}{\pi}  \Bigg[ \tan^{-1}(0) - \frac{\pi}{2} \Bigg] \\
&= \frac{1}{\pi}  \Bigg[ 0- \frac{\pi}{2} \Bigg] \\
&= \frac{1}{2} \\
P(X \ge 0) 
&= 1 - P(X \le 0) \\
&= 1 - F(0) \\
&= 1- \frac{1}{2} \\
&= \frac{1}{2}
\end{align*}

Thus, $m=0$.

5. Show that if $X$ is a continuous random variable, then $\min_a E|X - a| = E|x-m|$, where $m$ is the median of $X$.

\begin{align*}
E|X - a| 
&= \int_{-\infty}^{\infty}|t-a|f(t)dt \\
&= \int_{-\infty}^{a}(a-t)f(t)dt + \int_{a}^{\infty}(t-a)f(t)dt \\
&= \int_{-\infty}^{a}af(t)dt - \int_{-\infty}^{a}tf(t)dt + \int_{a}^{\infty}tf(t)dt - \int_{a}^{\infty}af(t)dt \\
&= a \Bigg( \int_{-\infty}^{a}f(t)dt - \int_{a}^{\infty}f(t)dt \Bigg)  - \Bigg(\int_{-\infty}^{a}tf(t)dt - \int_{a}^{\infty}tf(t)dt \Bigg)\\
&= a \Bigg( F(a) - (1-F(a)) \Bigg)  - \Bigg(\int_{-\infty}^{a}tf(t)dt - \int_{a}^{\infty}tf(t)dt \Bigg)\\
&= a \Bigg( 2F(a) - 1 \Bigg)  - \Bigg(\int_{-\infty}^{a}tf(t)dt - \int_{a}^{\infty}tf(t)dt \Bigg)\\
\end{align*}

Notice that this expression for $E|X - a|$ is differentiable by $a$.  Consider first the second half:

\begin{align*}
\frac{d}{da}\Bigg(\int_{-\infty}^{a}tf(t)dt - \int_{a}^{\infty}tf(t)dt \Bigg) 
&= af(a)-af(a) 
&=0
\end{align*}

Then the full expression:

\begin{align*}
\frac{d}{da}E|X - a| 
&= \frac{d}{da}a\Bigg( 2F(a) - 1 \Bigg) + 0 \\
&= \Bigg( 2F(a) - 1 \Bigg)
\end{align*}

Setting the derivative equal to zero:

\begin{align*}
2F(a) - 1 &= 0 \\
F(a) &= \frac{1}{2}
\end{align*}

Thus, $a = m$ where $P(X \ge m)=P(X \le m)=F(m)=\frac{1}{2}$.

\pagebreak

6. Let $\mu_n$ denote the $n$th central moment of a random variable $X$.  Two quantities of interest in addition to the mean and variance are $\alpha_3 = \frac{\mu_3}{\mu_2^{3/2}}$ and $\alpha_4 = \frac{\mu_4}{\mu_2^2}$.  The value $\alpha_3$ is called the skewness and $\alpha_4$ is called the kurtosis. The skewness measures the lack of symmetry in the density function.  The kurtosis, although harder to interpret, measures the peakedness or flatness of the density function.

(a) Show that if a density function is symmetric about a point $a$, then $\alpha_3 = 0$.

Proof: Define $Y=X-a$.  $Y$ has a symmetric distribution about zero $\implies E[Y^3]=E[(-Y)^3]=-E[Y^3]=0$ and $E[Y]=0$.  Thus, the 3rd central moment of $X$ is zero:

\begin{align*}
\mu_3 &= E[(X-E(X))^3] \\
      &= E[(Y+a-E(Y+a))^3] \\
      &= E[(Y+a-E(Y)-a)^3] \\
      &= E[(Y-E(Y))^3] \\
      &= E[Y^3] \\
      &= 0 \\
\end{align*}

Therefore, the skewness of $X$ is zero: $\alpha_3 = \frac{0}{\mu_2^{3/2}}=0$. $\square$

(b) Calculate $\alpha_3$ for $f(x) = \exp(-x), x \ge 0$, a density function that is skewed to the right.

\begin{align*}
M_X(t) &= E[e^{tx}] \\
       &= \int_0^\infty e^{tx}e^{-x} dx\\
       &= \int_0^\infty e^{-x(1-t)} dx\\
       &= \Bigg[ \frac{e^{-x(1-t)}}{1-t}(-1) \Bigg]_0^\infty\\
       &= \frac{0}{1-t}(-1)-\frac{1}{1-t}(-1)\\
       &= (1-t)^{-1}\\
\end{align*}

where $0\le t<1$.

\begin{align*}
M_X^{(1)}(t) &= (-1)(1-t)^{-2}(-1)\\
             &= (1-t)^{-2}\\
M_X^{(2)}(t) &= (-2)(1-t)^{-3}(-1)\\
             &= 2(1-t)^{-3}\\
M_X^{(3)}(t) &= (-3)2(1-t)^{-4}(-1) \\
             &= 6(1-t)^{-4} \\
\end{align*}

The first, second, and third moments of $X$ are:

\begin{align*}
E[X] &= M_X^{(1)}(0)=1 \\
E[X^2] &= M_X^{(2)}(0)=2 \\
E[X^3] &= M_X^{(3)}(0)=6 \\
\end{align*}

The second and third central moments of $X$ are:

\begin{align*}
\mu_2 
&= E[(X-E(X))^2] \\
&= E(X^2)-E(X)^2 \\
&= 2 - 1 \\
&= 1\\
\mu_3 
&= E[(X-E(X))^3] \\
&= E[(X-E(X))(X^2-2XE(X)+E(X)^2)]\\
&= E[X^3-2X^2E(X)+XE(X)^2-E(X)X^2+2XE(X)^2-E(X)^3]\\
&= E(X^3)-2E(X^2)E(X)+E(X)E(X)^2-E(X)E(X^2)+2E(X)E(X)^2-E(X)^3\\
&= (6)-2(2)(1)+(1)(1)^2-(1)(2)+2(1)(1)^2-(1)^3\\
&= 6-4+1-2+2-1\\
&= 2
\end{align*}

Skewness of $X$ is

\begin{align*}
\alpha_3 
&= \frac{\mu_3}{\mu_2^{3/2}}\\
&= \frac{2}{1^{3/2}}\\
&= 2\\
\end{align*}

(c) Calculate $\alpha_4$ for the following density functions and comment on the peakedness of each:

\begin{align}
f(x) &= \frac{1}{\sqrt{2 \pi}}\exp(-x^2/2), x \in \R \\
f(x) &= 1/2, x \in (-1, 1) \\
f(x) &= \frac{1}{2}\exp(-|x|), x \in \R
\end{align}